### ISSUE TITLE
数据库用sqlserver启动时报错

### ISSUE THREAD

**Issue by zhenghua0102** [zhangdaiscott/jeecg-boot#1031]
##### 版本号：
2.1.4

##### 问题描述：
数据库用sqlserver启动时报错

##### 截图&代码：

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-03-25 23:03:24.425 [main] ERROR org.springframework.boot.SpringApplication:858 - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'quartzScheduler'; nested exception is org.springframework.scheduling.SchedulingException: Could not start Quartz Scheduler; nested exception is org.quartz.SchedulerConfigException: Failure occured during job recovery. [See nested exception: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: sql injection violation, syntax error: syntax error, not support option : UPDATE, pos 90, line 1, column 84, token UPDATE : SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [See nested exception: java.sql.SQLException: sql injection violation, syntax error: syntax error, not support option : UPDATE, pos 90, line 1, column 84, token UPDATE : SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE]]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.jeecg.JeecgApplication.main(JeecgApplication.java:28)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhenghua0102** [comment]
修改配置文件  
## quartz定时任务,采用数据库方式
  quartz:
     job-store-type: jdbc
     properties:
       org:
         quartz:
           jobStore:
             selectWithLockSQL: SELECT* FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?
![image](https://user-images.githubusercontent.com/17560294/77600450-f52b4600-6f42-11ea-8c12-88f4020fb107.png)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273971
