### ISSUE TITLE
当添加 spring-boot-devtools 的时候报错 Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method org.jeecg.modules.online.cgform.service.impl.d

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#1058]
##### 版本号：
2.1.4

##### 问题描述：

为了开发方便，一般在开发环境会使用 spring-boot-devtools ，以便于修改文件的时候auto restart/ livereload ，详见 

https://www.codejava.net/frameworks/spring-boot/spring-boot-auto-reload-changes-using-livereload-and-devtools
https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/html/using-boot-devtools.html

在 jeecg-boot\jeecg-boot-module-system\pom.xml 中添加
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
```

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2276718/78495817-660d0200-777c-11ea-9319-7012f124356b.png)

详细错误信息如下
<details>
<summary>详细日志</summary>

```
2020-04-05 20:19:12.085 [restartedMain] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore:145 - JobStoreCMT initialized.
2020-04-05 20:19:12.087 [restartedMain] INFO  org.quartz.core.QuartzScheduler:294 - Scheduler meta-data: Quartz Scheduler (v2.3.0) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is not clustered. 

2020-04-05 20:19:12.101 [restartedMain] INFO  org.quartz.impl.StdSchedulerFactory:1362 - Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2020-04-05 20:19:12.103 [restartedMain] INFO  org.quartz.impl.StdSchedulerFactory:1366 - Quartz scheduler version: 2.3.0
2020-04-05 20:19:12.121 [restartedMain] INFO  org.quartz.core.QuartzScheduler:2287 - JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@1d9950cb
2020-04-05 20:19:14.533 [restartedMain] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:557 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/Liu.D.H/.m2/repository/org/hibernate/hibernate-re/2.1.4/hibernate-re-2.1.4.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
2020-04-05 20:19:14.536 [restartedMain] INFO  o.s.scheduling.quartz.SchedulerFactoryBean:844 - Shutting down Quartz Scheduler
2020-04-05 20:19:14.553 [restartedMain] INFO  org.quartz.core.QuartzScheduler:666 - Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
2020-04-05 20:19:14.556 [restartedMain] INFO  org.quartz.core.QuartzScheduler:585 - Scheduler quartzScheduler_$_NON_CLUSTERED paused. 
2020-04-05 20:19:14.558 [restartedMain] INFO  org.quartz.core.QuartzScheduler:740 - Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-04-05 20:19:14.567 [restartedMain] INFO  c.b.dynamic.datasource.DynamicRoutingDataSource:182 - closing dynamicDatasource  ing....
2020-04-05 20:19:14.574 [restartedMain] INFO  com.alibaba.druid.pool.DruidDataSource:1948 - {dataSource-1} closing ...
2020-04-05 20:19:14.594 [restartedMain] INFO  com.alibaba.druid.pool.DruidDataSource:2020 - {dataSource-1} closed
2020-04-05 20:19:14.629 [restartedMain] INFO  org.apache.catalina.core.StandardService:173 - Stopping service [Tomcat]
2020-04-05 20:19:14.667 [restartedMain] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-05 20:19:14.704 [restartedMain] ERROR org.springframework.boot.SpringApplication:858 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/Liu.D.H/.m2/repository/org/hibernate/hibernate-re/2.1.4/hibernate-re-2.1.4.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) 
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.jeecg.JeecgApplication.main(JeecgApplication.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
        at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:214)
        at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471)        
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350)    
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        ... 20 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
        at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
        at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:58)       
        at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205)
        ... 27 common frames omitted
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$fd8d686e.addAll(Lorg/jeecg/modules/online/cgform/model/b;)Lorg/jeecg/common/api/vo/Result;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, org/jeecg/modules/online/cgform/service/impl/d$$EnhancerBySpringCGLIB$$fd8d686e, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type org/jeecg/common/api/vo/Result used in the signature
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:537)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        ... 34 common frames omitted
```
</details>

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
我试着升级 spring-boot-starter-parent 到 2.1.13.RELEASE 或者 2.2.6.RELEASE 都还是一样的报错，查看反编译后的方法签名，似乎没有问题。

与这个类似的有 https://github.com/AxonFramework/AxonFramework/issues/1061 但不完全一样

感觉像是classloader里面有两个 org/jeecg/common/api/vo/Result

**Comment by liudonghua123** [comment]
看了一下官方文档，似乎有点小明白，使用 spring-boot-devtools 的时候，不常用的class（一般是项目依赖的jar包）会使用 base classloader，项目里面自己写的class会使用 restart classloader，两个classloader如果有一些共享的class，可能会有问题，这一点还没想明白，需要配置把这些依赖的jar包也使用 restart classloader。
具体文档可参考 https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload

修改的地方是在 jeecg-boot\jeecg-boot-module-system\src\main\resources\META-INF 中添加 spring-devtools.properties ，里面的内容是
```
restart.include.hibernate-re=/hibernate-re-(.*).jar
```

最后吐槽一点，虽然 auto restart 可以加快速度，但还是比不了 auto reload，但auto reload的特性需要商业化的工具 例如 JRebel 才能支持，希望 JRebel 可以早点免费给所有Java开发者使用。
