### ISSUE TITLE
代码生成器这块的问题及建议

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#1061]
##### 版本号：
2.1.4

##### 问题描述：
代码生成器这块有在线开发中动态运行使用的模板以及一般生成代码的模板，两个模板文件夹里的模板相差比较大，我看有很多地方 code-template-online 里面的处理的较完善，code-template里的处理的较差，我复制code-template-online的模板到 code-template里面也可以运行，但还是会有一些问题和在线开发中看到的有区别，例如如果是树模型，在线开发里面是树形下来选择框，但生成的代码里面是普通输入框，我看代码主要是缺少这一块

```
  <#if po.fieldDbName == tableVo.extendParams.pidField>
    <#assign form_tree_select = true>
    <#assign pidFieldName = po.fieldName>
          <j-tree-select
            ref="treeSelect"
            placeholder="请选择${po.filedComment}"
            v-decorator="['${po.fieldName}', validatorRules.${po.fieldName}]"
            dict="${tableVo.tableName},${tableVo.extendParams.textField},id"
            pidField="${tableVo.extendParams.pidField}"
            pidValue="0"
            hasChildField="${tableVo.extendParams.hasChildren}">
          </j-tree-select>
```

但是我直接添加上运行报错，提示 tableVo.extendParams 有问题，可能是 tableVo 没有传进去

```
FreeMarker template error (DEBUG mode; use RETHROW in production!):
The following has evaluated to null or missing:
==> tableVo.extendParams  [in template "erp\\onetomany\\java\\${bussiPackage}\\${entityPackage}\\vue\\modules\\${entityName}Modal.vuei" at line 35, column 26]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if po.fieldDbName == tableVo.extendP...  [in template "erp\\onetomany\\java\\${bussiPackage}\\${entityPackage}\\vue\\modules\\${entityName}Modal.vuei" at line 35, column 3]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
	at freemarker.core.NonHashException.<init>(NonHashException.java:49)
	at freemarker.core.Dot._eval(Dot.java:48)
```

希望代码生成器这块可以简化普通模式、在线开发模式，两者尽量较少差异，改善代码质量，重构增加可复用性，这样代码可以降低维护成本、开发成本。

##### 截图&代码：
无

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by liudonghua123** [comment]
还发现一个小问题
jeecg-boot\jeecg-boot-module-system\src\main\resources\jeecg\code-template-online\erp\onetomany\java\${bussiPackage}\${entityPackage}\vue\${entityName}List.vuei#170

如果是表名有前缀，和entity不一样，那生成的代码会有问题，需要修改这里的 

<${sub.tableName?replace("_","-")}-list :mainId="selectedMainId" />

改为

<${sub.entityName?replace("_","-")}-list :mainId="selectedMainId" />

这些都是一些零零碎碎的小问题，例如还有生成的entity上的注解，有的有swagger的注解，有的没有，如果绝大多数都是共用可复用的代码，那么就可以很好的解决处理这些问题

**Comment by zhangdaiscott** [comment]
两边的模板不通用，你用法错误
