### ISSUE TITLE
mac 中前端项目压缩报错

### ISSUE THREAD

**Issue by GaoKeiis** [zhangdaiscott/jeecg-boot#1081]
##### 版本号：
vue-antd-jeecg@2.1.4

##### 问题描述：
mac 中前端项目压缩报错

##### 截图&代码：

 Building for production... ERROR  TypeError: Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/gaoningning/Desktop/jeecg-boot/Report/node_modules/mini-css-extract-plugin/dist/CssDependency.js:12:46)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/gaoningning/Desktop/jeecg-boot/Report/node_modules/mini-css-extract-plugin/dist/index.js:12:45)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-antd-jeecg@2.1.4 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-antd-jeecg@2.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gaoningning/.npm/_logs/2020-04-11T07_56_16_553Z-debug.log

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zheyvsu** [comment]
同样问题。 解决了吗？
不仅仅是mac

**Comment by GaoKeiis** [comment]
> 同样问题。解决了吗？
> 不仅仅是MAC

解决了webpack的版本问题，从新更新webpack为最新的版本
npm install webpack webpack-cli webpack-dev-server webpack-merge --save-dev
