### ISSUE TITLE
前端项目npm run build的时候，报错TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by CodingJason** [zhangdaiscott/jeecg-boot#1135]
##### 版本号：
master分支
2.1.4

##### 问题描述：
前端项目可以npm run serve，但是npm run build的时候，报错
TypeError: Class extends value undefined is not a constructor or null
如果需要别的信息请给我说。
##### 截图&代码：
```
⠋  Building for production... ERROR  TypeError: Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/jason/Documents/shenjiajia/jeecg-boot/ant-design-vue-jeecg/node_modules/mini-css-extract-plugin/dist/CssDependency.js:12:46)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jason/Documents/shenjiajia/jeecg-boot/ant-design-vue-jeecg/node_modules/mini-css-extract-plugin/dist/index.js:12:45)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```
![image](https://user-images.githubusercontent.com/3403239/80476704-52207e80-897d-11ea-8960-bcc9c6acda71.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用yarn 或者 cnpm

**Comment by CodingJason** [comment]
使用yarn可以build了。

**Comment by helibin** [comment]
为什么用yarn或cnpm就可以，npm不应该都可以才对吗

**Comment by helibin** [comment]
更新下mini-css-extract-plugin版本，
npm i -D mini-css-extract-plugin@2.3.0
可使用npm install + npm run build

**Comment by helibin** [comment]
> 为什么用yarn或cnpm就可以，npm不应该都可以才对吗

更新下mini-css-extract-plugin版本，
npm i -D mini-css-extract-plugin@2.3.0
可使用npm install + npm run build
