### ISSUE TITLE
前端编译问题

### ISSUE THREAD

**Issue by mayqxp** [zhangdaiscott/jeecg-boot#1160]
##### 问题描述：
npm install 没有问题。npm run serve 也没问题。
执行 npm run build 就会报错：
⠋  Building for production... ERROR  TypeError: Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/root/test/jeecg/node_modules/mini-css-extract-plugin/dist/CssDependency.js:12:46)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\java_idea\pz_project\my-jeecg-boot\ant-design-vue\node_modules\mini-css-extract-plugin\dist\index.js:12:45)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

windows操作系统
# node -v
v12.13.0
# npm -v
6.12.0

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3906633/81166216-f0d45d00-8fc5-11ea-8b28-a36221823102.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
依赖删掉，用yarn install
