### ISSUE TITLE
springboot 热部署 引入以后，项目启动报错

### ISSUE THREAD

**Issue by CSuperC** [zhangdaiscott/jeecg-boot#1191]
##### 版本号：
2.2 版本

##### 问题描述：
引入springboot 热部署，启动以后报错

##### 截图&代码：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/admin/.m2/repository/org/hibernate/hibernate-re/2.1.5/hibernate-re-2.1.5.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
         at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$145/112251205.getObject(Unknown Source)
         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
         at org.jeecg.JeecgApplication.main(JeecgApplication.java:35)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:483)
         at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
         at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:214)
         at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
         at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471)
         at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350)
         at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
         ... 21 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
         at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
         at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
         at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
         at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
         at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
         at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:58)
         at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205)
         ... 28 common frames omitted
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$a6139eea.addAll(Lorg/jeecg/modules/online/cgform/model/a;)Lorg/jeecg/common/api/vo/Result;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, org/jeecg/modules/online/cgform/service/impl/d$$EnhancerBySpringCGLIB$$a6139eea, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type org/jeecg/common/api/vo/Result used in the signature
         at java.lang.Class.forName0(Native Method)
         at java.lang.Class.forName(Class.java:344)
         at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:537)
         at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
         at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
         at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
         ... 35 common frames omitted

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不要用springboot的热插件，用jrebel

**Comment by CSuperC** [comment]
@zhangdaiscott 
明天尝试下 jrebel
但是个人感觉，对咱们jeecg-boot 更好的推广，希望，下个版本兼容下devtools，hibernate-re 的cglib代理报的错，同时，咱们的springboot的版本，希望跟官方同步，升级，现在2.1.3的boot 稍微有点老，都是为了jeecg 更好的发展
