### ISSUE TITLE
返回vo 报错

### ISSUE THREAD

**Issue by CSuperC** [zhangdaiscott/jeecg-boot#1254]
##### 截图&代码：
    Caused by: java.lang.NoSuchMethodError: org.jeecg.common.api.vo.Result.setSuccess(Z)V
         at org.jeecg.modules.online.cgform.b.d.a(OnlCgformHeadController.java:94)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:497)
         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
         ... 79 common frames omitted

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by CSuperC** [comment]
用的idea ，然后跟踪代码，有lombok的包，这个方法也有，也跟踪到了，但是提示，nosuchmethod ，非常奇怪

**Comment by CSuperC** [comment]
问题找到了，是因为@Accessors(chain = true)  lombok 表达式的问题，去掉这块就行了，开源默认没有这个配置，我自己加上然后制造了这个问题
