### ISSUE TITLE
获取通知报错 admin/ 123456

### ISSUE THREAD

**Issue by kangshifu1** [zhangdaiscott/jeecg-boot#127]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'userId' not found. Available parameters are [arg2, arg1, arg0, param3, param1, param2]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy134.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.executeForMany(PageMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.PageMapperMethod.execute(PageMapperMethod.java:86)
	at com.baomidou.mybatisplus.core.override.PageMapperProxy.invoke(PageMapperProxy.java:64)
	at com.sun.proxy.$Proxy175.querySysCementListByUserId(Unknown Source)
	at org.jeecg.modules.system.service.impl.SysAnnouncementServiceImpl.querySysCementPageByUserId(SysAnnouncementServiceImpl.java:117)
	at org.jeecg.modules.system.service.impl.SysAnnouncementServiceImpl$$FastClassBySpringCGLIB$$4d089368.invoke(<generated>)

**Comment by zhangdaiscott** [comment]
更新下代码，刚上传了
