### ISSUE TITLE
Table 中 批量 删除数据报错 

### ISSUE THREAD

**Issue by LiuNet2** [zhangdaiscott/jeecg-boot#1274]
##### 版本号：
最新的版本 2.2

##### 问题描述：

前端 table 批量删除数据，数量569条，后台报错

2020-05-31 22:44:12.500 [http-nio-8080-exec-7] INFO  org.apache.coyote.http11.Http11Processor:175 - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:718)
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:448)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

##### 截图&代码：

![Uploading image.png…]()

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
图片错误
