### ISSUE TITLE
访问 /doc.html  报错

### ISSUE THREAD

**Issue by kangshifu1** [zhangdaiscott/jeecg-boot#128]
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)

**Comment by zhangdaiscott** [comment]
暂时不影响使用
