### ISSUE TITLE
项目依赖包外置，无法导入excel

### ISSUE THREAD

**Issue by CarlJia** [zhangdaiscott/jeecg-boot#1292]
##### 版本号：
2.2.0

##### 问题描述：
nginx+jar包方式 部署在服务器上，excel导入报错

##### 截图&代码：
导入 excel，后台报错

```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.jeecgframework.poi.util.PoiPublicUtil.getWebRootPath(PoiPublicUtil.java:318)
	at org.jeecgframework.poi.excel.imports.base.ImportBaseService.saveThisExcel(ImportBaseService.java:248)
	at org.jeecgframework.poi.excel.imports.ExcelImportServer.importExcelByIs(ExcelImportServer.java:411)
	at org.jeecgframework.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:85)
	at org.jeecg.modules.demo.common.service.IExcelImportService.doImport(IExcelImportService.java:42)
	at org.jeecg.modules.demo.bdm.service.impl.PubGoodsServiceImpl.importExcel(PubGoodsServiceImpl.java:73)
	at org.jeecg.modules.demo.bdm.service.impl.PubGoodsServiceImpl$$FastClassBySpringCGLIB$$a30554a4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.jeecg.modules.demo.bdm.service.impl.PubGoodsServiceImpl$$EnhancerBySpringCGLIB$$880cdf6d.importExcel(<generated>)
	at org.jeecg.modules.demo.bdm.controller.PubGoodsController.importExcel(PubGoodsController.java:204)
	at org.jeecg.modules.demo.bdm.controller.PubGoodsController$$FastClassBySpringCGLIB$$892dcd8a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.jeecg.modules.system.aspect.DictAspect.doAround(DictAspect.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```
pom.xml
```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.jeecg.JeecgApplication</mainClass>
                            <!-- 入口程序 -->
                            <addClasspath>true</addClasspath>
                            <!-- 添加依赖jar路径 -->
                            <classpathPrefix>lib/</classpathPrefix>
                        </manifest>

                    </archive>
                </configuration>
            </plugin>
```
代码定位可能是在 PoiPublicUtil 类
```
    public static String getWebRootPath(String filePath) {
        try {
            String path = null;

            try {
                path = PoiPublicUtil.class.getClassLoader().getResource("").toURI().getPath();
            } catch (URISyntaxException var3) {
            }

            if (path == null || path == "") {
                path = ClassUtils.getDefaultClassLoader().getResource("").getPath();
            }

            LOGGER.debug("--- getWebRootPath ----filePath--- " + path);
            path = path.replace("WEB-INF/classes/", "");
            path = path.replace("file:/", "");
            LOGGER.debug("--- path---  " + path);
            LOGGER.debug("--- filePath---  " + filePath);
            return path + filePath;
        } catch (Exception var4) {
            throw new RuntimeException(var4);
        }
    }
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
autopoi的版本是多少

**Comment by CarlJia** [comment]
> autopoi的版本是多少

![image](https://user-images.githubusercontent.com/7962229/83737396-84608280-a685-11ea-869d-921c68227c7f.png)
autopoi 1.1.1

**Comment by zhangdaiscott** [comment]
确认下发布线上你的autopoi版本，这个问题老版存在，
1.1.1 很早已经处理

**Comment by smt2235** [comment]
遇到同样的问题，线上是1.2.2版本，估计也是外置lib包导致的
