### ISSUE TITLE
controller方法参数列表中带有HttpServletRequest类型参数，执行完成后，保存日志报错

### ISSUE THREAD

**Issue by qingjing0606** [zhangdaiscott/jeecg-boot#1394]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/10215599/86068467-02a81d00-baaa-11ea-8c39-42ac5a723428.png)

java.lang.IllegalStateException: It is illegal to call this method if the current request is not in asynchronous mode (i.e. isAsyncStarted() returns false)
	at org.apache.catalina.connector.Request.getAsyncContext(Request.java:1758)
	at org.apache.catalina.connector.RequestFacade.getAsyncContext(RequestFacade.java:1068)
	at javax.servlet.ServletRequestWrapper.getAsyncContext(ServletRequestWrapper.java:435)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_ShiroHttpServletRequest.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:333)
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:311)
	at com.alibaba.fastjson.serializer.ObjectArrayCodec.write(ObjectArrayCodec.java:118)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:745)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:683)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:648)
	at org.jeecg.modules.system.aspect.AutoLogAspect.getReqestParams(AutoLogAspect.java:147)
	at org.jeecg.modules.system.aspect.AutoLogAspect.saveSysLog(AutoLogAspect.java:88)

src/main/java/org/jeecg/modules/system/aspect/AutoLogAspect.java
![image](https://user-images.githubusercontent.com/10215599/86069043-5f580780-baab-11ea-8d2e-d4ed27844309.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
待测试

**Comment by 1298191366** [comment]
新版本已修改
