### ISSUE TITLE
导出excel实体反射，时间格式转换错误

### ISSUE THREAD

**Issue by herosql** [zhangdaiscott/jeecg-boot#1573]
##### 版本号：
autopoi:1.1.1

##### 问题描述：
在实体映射中定义其他@ExcelEntity 实体，普通字段不受影响，时间字段会转换异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/39084622/89750723-c54e9a80-daff-11ea-826c-faccdbb3db4b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
请在细化下问题描述

**Comment by zhangdaiscott** [comment]
导出excel实体反射，时间格式转换错误 #1573
https://github.com/zhangdaiscott/jeecg-boot/issues/1573

BUG复现 @ExcelEntity标记的实体类中Date类型的属性值为null/空字符串时，抛出该异常
2020-08-31 02:10:53.988 [http-nio-8080-exec-3] ERROR o.j.poi.excel.export.ExcelExportServer:193 - Unparseable date: ""
java.text.ParseException: Unparseable date: ""
at java.text.DateFormat.parse(DateFormat.java:366)
at org.jeecgframework.poi.excel.export.base.ExportBase.formatValue(ExportBase.java:77)
at org.jeecgframework.poi.excel.export.base.ExportBase.getCellValue(ExportBase.java:178)
at org.jeecgframework.poi.excel.export.base.ExcelExportBase.createCells(ExcelExportBase.java:113)
...
解决方案
autopoi版本 1.2 value为空值时提前 return

org.jeecgframework.poi.excel.export.base.ExportBase#getCellValue

public Object getCellValue(ExcelExportEntity entity, Object obj) throws Exception {
    Object value;
    if (obj instanceof Map) {
        value = ((Map<?, ?>) obj).get(entity.getKey());
    } else {
        value = entity.getMethods() != null ? getFieldBySomeMethod(entity.getMethods(), obj) : entity.getMethod().invoke(obj, new Object[] {});
    }
    // +++
    value = Optional.ofNullable(value).orElse("");
    if (StringUtils.isEmpty(value.toString())) {
        return "";
    }
    // +++
}
