### ISSUE TITLE
数据库QRTZ_LOCKS表真实存在 异常提示 Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist

### ISSUE THREAD

**Issue by DuanFuzhou** [zhangdaiscott/jeecg-boot#162]
Caused by: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:157)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3842)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverJobs(JobStoreSupport.java:839)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.schedulerStarted(JobStoreSupport.java:695)
	... 19 common frames omitted

**Comment by zhangdaiscott** [comment]
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1
10

**Comment by SheepYang1993** [comment]
参考：https://www.sheepyang1993.com/archives/20200604

**Comment by kuchaguangjie** [comment]
表名 明明是小写, sql 非得 写成 大写, 自找麻烦 ...

**Comment by hzdavid** [comment]
是啊，为什么要自找麻烦啊？@ShepYang1993 @SheepYang1993 @zhangdaiscott
