### ISSUE TITLE
自定义新建模块启动报错

### ISSUE THREAD

**Issue by Goshirt** [zhangdaiscott/jeecg-boot#1806]
##### 版本号：
使用的版本为：2.3

##### 问题描述：
在原有项目基础上（system模块和jeecg-demo模块已经成功启动），新建一个模块，但没有使用org.jeecg 作为包名时，启动失败
我使用的模块包名为com.helmet，启动类也加上了`@ComponentScan({"org.jeecg.*", "com.helmet.*"})`
##### 截图&代码：
1. 新建模块目录结构截图
![image](https://user-images.githubusercontent.com/26708885/94331852-89fe2180-0002-11eb-9a6c-049a35f5664d.png)

2. pom.xml 文件依赖
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jeecg-boot-parent</artifactId>
        <groupId>org.jeecgframework.boot</groupId>
        <version>2.3.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.helmet</groupId>
    <artifactId>helmet-module-demo</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-boot-base-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-system-cloud-api</artifactId>
        </dependency>
    </dependencies>
</project>
```
3. 启动类代码
```
package com.helmet;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.context.annotation.ComponentScan;

import java.net.UnknownHostException;

@ComponentScan({"org.jeecg.*", "com.helmet.*"})
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
@EnableAutoConfiguration(exclude={org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class})
public class HelmetDemoApplication {

    public static void main(String[] args) throws UnknownHostException {
        SpringApplication.run(HelmetDemoApplication.class, args);
    }
}
```
4. 启动时报错信息
```
2020-09-26 14:08:22.860  INFO 17792 --- [           main] c.b.d.d.DynamicDataSourceCreator         : 动态数据源-检测到druid存在,如配置中未指定type,druid会默认配置
2020-09-26 14:08:23.027  INFO 17792 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1,master} inited
2020-09-26 14:08:23.027  INFO 17792 --- [           main] c.b.d.d.DynamicRoutingDataSource         : 初始共加载 1 个数据源
2020-09-26 14:08:23.027  INFO 17792 --- [           main] c.b.d.d.DynamicRoutingDataSource         : 动态数据源-加载 master 成功
2020-09-26 14:08:23.027  INFO 17792 --- [           main] c.b.d.d.DynamicRoutingDataSource         : 当前的默认数据源是单数据源，数据源名为 master
2020-09-26 14:08:24.303  WARN 17792 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dictAspect': Unsatisfied dependency expressed through field 'commonAPI'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2020-09-26 14:08:24.303  INFO 17792 --- [           main] c.b.d.d.DynamicRoutingDataSource         : closing dynamicDatasource  ing....
2020-09-26 14:08:24.306  INFO 17792 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2020-09-26 14:08:24.308  INFO 17792 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2020-09-26 14:08:24.321  INFO 17792 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-09-26 14:08:24.323  WARN 17792 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [spring.cloud.inetutils] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.Inet6AddressImpl.getHostByAddr(Native Method)
 java.net.InetAddress$2.getHostByAddr(InetAddress.java:932)
 java.net.InetAddress.getHostFromNameService(InetAddress.java:617)
 java.net.InetAddress.getHostName(InetAddress.java:559)
 java.net.InetAddress.getHostName(InetAddress.java:531)
 org.springframework.cloud.commons.util.InetUtils$$Lambda$64/1264213713.call(Unknown Source)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2020-09-26 14:08:24.323  WARN 17792 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [logback-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2020-09-26 14:08:24.324  WARN 17792 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.naming.client.listener] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
 com.alibaba.nacos.client.naming.core.EventDispatcher$Notifier.run(EventDispatcher.java:114)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2020-09-26 14:08:24.324  WARN 17792 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.naming.failover] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2020-09-26 14:08:24.324  WARN 17792 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.naming.push.receiver] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
 java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:124)
 java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
 java.net.DatagramSocket.receive(DatagramSocket.java:812)
 com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:73)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
2020-09-26 14:08:24.337  INFO 17792 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-09-26 14:08:24.498 ERROR 17792 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dictAspect': Unsatisfied dependency expressed through field 'commonAPI'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at com.helmet.HelmetDemoApplication.main(HelmetDemoApplication.java:20) [classes/:na]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1654) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1213) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 19 common frames omitted


Process finished with exit code 1
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lvjunjie-byte** [comment]
我也遇到一样的问题，有解决的吗

**Comment by Goshirt** [comment]
@EnableFeignClients 加上包扫描，可以解决

**Comment by Goshirt** [comment]
> 我也遇到一样的问题，有解决的吗
我的在@EnableFeignClients 加上包扫描可以解决了

**Comment by rillzhang** [comment]
> > 我也遇到一样的问题，有解决的吗
> > 我的在@EnableFeignClients 加上包扫描可以解决了

用的单体模式，不是微服务模式。

**Comment by c-java-father** [comment]
用的单体模式，不是微服务模式。遇到同样问题

**Comment by zhangdaiscott** [comment]
单体模块，不应该是引入system里面吗，启动system

**Comment by darkmi** [comment]
在自建模块里引入 jeecg-base-core模块就可以了。

**Comment by zhubinsheng** [comment]
这个问题应该杯打开更新讨论

**Comment by asdfghjklor** [comment]
> 用的单体模式，不是微服务模式。遇到同样问题 用eclipse可以启动，jar命令启动不行 Field commonAPI in org.jeecg.common.aspect.PermissionDataAspect required a bean of type 'org.jeecg.common.api.CommonAPI' that could not be found.

有解决吗？到底是什么问题？

**Comment by asdfghjklor** [comment]
> 用的单体模式，不是微服务模式。遇到同样问题 用eclipse可以启动，jar命令启动不行 Field commonAPI in org.jeecg.common.aspect.PermissionDataAspect required a bean of type 'org.jeecg.common.api.CommonAPI' that could not be found.

这个问题最后解决了吗？

**Comment by chy06201** [comment]
这个问题解决了吗

**Comment by qtfour** [comment]
这个问题解决了吗!!!同问！！！

**Comment by qtfour** [comment]
> 

不是微服务不支持独立启动，需要在system引入新建maven，启动system

https://github.com/jeecgboot/jeecg-boot/issues/3247 
这里官网回复

**Comment by asdfghjklor** [comment]
我的没问题了，你具体是什么问题？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月13日(周四) 中午11:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 自定义新建模块启动报错 (#1806)




 
这个问题解决了吗!!!同问！！！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wileywu** [comment]
> 我的没问题了，你具体是什么问题？
> […](#)

你是怎么解决的？

**Comment by asdfghjklor** [comment]
我应该也是没问题了，我都记不得具体问题是什么了。




Sun&nbsp;Yue
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月19日(星期一) 上午10:09
***@***.***&gt;;
抄送:&nbsp;"Sun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 自定义新建模块启动报错 (#1806)





  
我的没问题了，你具体是什么问题？
 …
  
你是怎么解决的？

**Comment by xzy1224** [comment]
到底怎么解决的？单体模式：No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available

**Comment by zhangdaiscott** [comment]
maven clean install
