### ISSUE TITLE
前端打包问题

### ISSUE THREAD

**Issue by mark0614** [zhangdaiscott/jeecg-boot#1861]
##### 版本号：

2.3
##### 问题描述：
执行yarn install    yarn run build 之后报错：ERROR  RangeError: Unsupported time zone specified undefined
操作场景：在Jenkins中使用Excute shell方式进行构建（在本机开发，使用Idea进行）

##### 截图&代码：
-  Building for production...
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
 ERROR  RangeError: Unsupported time zone specified undefined
RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at Debugger.title (/var/jenkins_home/workspace/teee/node_modules/@soda/friendly-errors-webpack-plugin/src/output.js:54:42)
    at FriendlyErrorsWebpackPlugin.displayErrors (/var/jenkins_home/workspace/teee/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:105:12)
    at doneFn (/var/jenkins_home/workspace/teee/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/jenkins_home/workspace/teee/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/var/jenkins_home/workspace/teee/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/var/jenkins_home/workspace/teee/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/var/jenkins_home/workspace/teee/node_modules/webpack/lib/Compiler.js:499:39)
    at emitAssets.err (/var/jenkins_home/workspace/teee/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/var/jenkins_home/workspace/teee/node_modules/webpack/lib/Compiler.js:485:14)
    at _next0 (eval at create (/var/jenkins_home/workspace/teee/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at _err0 (eval at create (/var/jenkins_home/workspace/teee/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at callback (/var/jenkins_home/workspace/teee/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/var/jenkins_home/workspace/teee/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/jenkins_home/workspace/teee/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by mark0614** [comment]
这个问题我解决了，是我的nodejs的版本太低
