### ISSUE TITLE
求助：后端控制前台页面重定向问题

### ISSUE THREAD

**Issue by onewaymail1** [zhangdaiscott/jeecg-boot#1942]
##### 问题描述：
需求描述：
概述：通过后端页面控制页面重定向，但是前后台分离后，重定向总是在后台的localhost:8080/xxx/xxx 进行，无法控制跳转到localhost:3000/dashboard/analysis

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8220565/98427640-e875ef80-20d8-11eb-9bb3-fb49ec0e4c1c.png)

HttpClient.java
`
public class HttpClient {
    public String client(String url, HttpMethod method, MultiValueMap<String, String> parms) {
        RestTemplate template = new RestTemplate();
        ResponseEntity<String> response = template.getForEntity(url, String.class);
        return response.getBody();
    }
}
`
Controller:
iamTokenOauth.java

`@RequestMapping(value = "/oauth")
    @ApiOperation("登录接口")
    public ModelAndView iamTokenOauth(@RequestParam String code) {
        //Result<String> result = new Result<String>();
        Result<JSONObject> result = new Result<JSONObject>();
        //接收iam传过来的code ，并向iam服务器发送系统授权信息，请求token；
        //System.out.println("code:>>" + code + "appcode:" + appcode + "secret" + secret);
        String url = "http://test.com/ngiam-rst/oauth2/token?appcode=" + appcode + "&secret=" + secret + "&code=" + code;
        HttpMethod method = HttpMethod.GET;
        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        String token = httpClient.client(url, method, params);

        //业务系统得到accesstoken后携带参数访问IAM服务器，验证token有效性
        JSONObject jsonObject = JSONObject.parseObject(token);//String 转jsonObject
        String accessToken = jsonObject.getString("accessToken");
        String checkInfo = null;
        if (!accessToken.equals("") || !accessToken.isEmpty()) {
            String url2 = "http://test.com/ngiam-rst/oauth2/userinfo?appcode=" + appcode + "&secret=" + secret + "&token=" + accessToken;
            checkInfo = httpClient.client(url2, method, params);
            String username = JSONObject.parseObject(checkInfo).getString("accountName");//判断身份认证系统返回结果 是否为"true"  做登录操作；

            //1. 校验用户是否有效
            LambdaQueryWrapper<SysUser> queryWrapper = new LambdaQueryWrapper<>();
            queryWrapper.eq(SysUser::getUsername, username);
            SysUser sysUser = sysUserService.getOne(queryWrapper);
            result = sysUserService.checkUserIsEffective(sysUser);
            if (!result.isSuccess()) {
                return new ModelAndView("");
            }
            //用户登录信息
            userInfo(sysUser, result);
            LoginUser loginUser = new LoginUser();
            BeanUtils.copyProperties(sysUser, loginUser);
            baseCommonService.addLog("用户名: " + username + ",登录成功！", CommonConstant.LOG_TYPE_1, null, loginUser);
            ///dashboard/analysis
            return new ModelAndView("redirect:/dashboard/analysis");
        }
        return new ModelAndView("");
    }
   `
错误信息：

`
2020-11-07 08:54:24.004 [http-nio-8080-exec-1] INFO  o.j.modules.system.service.impl.SysDictServiceImpl:76 - -------登录加载系统字典-----{ol_form_biz_type=[DictModel(value=demo, text=官方示例), DictModel(value=bpm, text=流程表单), DictModel(value=temp, text=测试表单), DictModel(value=bdfl_include, text=导入表单)], msgType=[DictModel(value=4, text=系统), DictModel(value=1, text=短信), DictModel(value=2, text=邮件), DictModel(value=3, text=微信)], eoa_plan_status=[DictModel(value=0, text=未开始), DictModel(value=1, text=进行中), DictModel(value=2, text=已完成)], position_rank=[DictModel(value=1, text=员级), DictModel(value=2, text=助级), DictModel(value=3, text=中级), DictModel(value=4, text=副高级), DictModel(value=5, text=正高级)], rule_conditions=[DictModel(value=>, text=大于), DictModel(value=<, text=小于), DictModel(value=!=, text=不等于), DictModel(value==, text=等于), DictModel(value=>=, text=大于等于), DictModel(value=<=, text=小于等于), DictModel(value=LEFT_LIKE, text=左模糊), DictModel(value=RIGHT_LIKE, text=右模糊), DictModel(value=LIKE, text=模糊), DictModel(value=IN, text=包含), DictModel(value=USE_SQL_RULES, text=自定义SQL表达式)], ceshi_online=[DictModel(value=3, text=easyui), DictModel(value=1, text=booostrap), DictModel(value=00, text=000)], online_graph_data_type=[DictModel(value=sql, text=SQL), DictModel(value=json, text=JSON)], database_type=[DictModel(value=1, text=MySQL), DictModel(value=2, text=Oracle), DictModel(value=3, text=SQLServer)], online_graph_display_template=[DictModel(value=tab, text=Tab风格), DictModel(value=single, text=单排布局), DictModel(value=double, text=双排布局), DictModel(value=combination, text=组合布局)], log_type=[DictModel(value=2, text=操作日志), DictModel(value=1, text=登录日志)], user_type=[DictModel(value=333, text=333)], yn=[DictModel(value=0, text=否), DictModel(value=1, text=是)], send_status=[DictModel(value=0, text=未发布), DictModel(value=1, text=已发布), DictModel(value=2, text=已撤销)], eoa_cms_menu_type=[DictModel(value=1, text=列表), DictModel(value=2, text=链接)], tenant_status=[DictModel(value=1, text=正常), DictModel(value=0, text=冻结)], bpm_process_type=[DictModel(value=test, text=测试流程), DictModel(value=oa, text=OA办公), DictModel(value=business, text=业务办理)], form_perms_type=[DictModel(value=1, text=可见(未授权不可见)), DictModel(value=2, text=可编辑(未授权禁用))], valid_status=[DictModel(value=0, text=无效), DictModel(value=1, text=有效)], urgent_level=[DictModel(value=1, text=一般), DictModel(value=2, text=重要), DictModel(value=3, text=紧急)], del_flag=[DictModel(value=0, text=正常), DictModel(value=1, text=已删除)], user_status=[DictModel(value=1, text=正常), DictModel(value=2, text=冻结)], operate_type=[DictModel(value=1, text=查询), DictModel(value=2, text=添加), DictModel(value=3, text=修改), DictModel(value=4, text=删除), DictModel(value=5, text=导入), DictModel(value=6, text=导出)], quartz_status=[DictModel(value=0, text=正常), DictModel(value=-1, text=停止)], cgform_table_type=[DictModel(value=1, text=单表), DictModel(value=2, text=主表), DictModel(value=3, text=附表)], menu_type=[DictModel(value=2, text=按钮权限), DictModel(value=1, text=子菜单), DictModel(value=0, text=一级菜单)], sex=[DictModel(value=1, text=男), DictModel(value=2, text=女)], msg_category=[DictModel(value=2, text=系统消息), DictModel(value=1, text=通知公告)], org_category=[DictModel(value=3, text=岗位), DictModel(value=1, text=公司), DictModel(value=2, text=部门)], perms_type=[DictModel(value=1, text=显示), DictModel(value=2, text=禁用)], global_perms_type=[DictModel(value=1, text=可见/可访问(授权后可见/可访问)), DictModel(value=2, text=可编辑(未授权时禁用))], priority=[DictModel(value=H, text=高), DictModel(value=M, text=中), DictModel(value=L, text=低)], dict_item_status=[DictModel(value=1, text=启用), DictModel(value=0, text=不启用)], online_graph_type=[DictModel(value=bar, text=柱状图), DictModel(value=line, text=曲线图), DictModel(value=pie, text=饼图), DictModel(value=table, text=数据列表)], activiti_sync=[DictModel(value=1, text=同步), DictModel(value=0, text=不同步)], msgSendStatus=[DictModel(value=0, text=未发送), DictModel(value=1, text=发送成功), DictModel(value=2, text=发送失败)], msg_type=[DictModel(value=ALL, text=全体用户), DictModel(value=USER, text=指定用户)], bpm_status=[DictModel(value=1, text=待提交), DictModel(value=2, text=处理中), DictModel(value=3, text=已完成), DictModel(value=4, text=已作废)], eoa_plan_type=[DictModel(value=1, text=日常记录), DictModel(value=2, text=本周工作), DictModel(value=3, text=下周计划)], depart_status=[DictModel(value=0, text=不启用), DictModel(value=1, text=启用)], status=[DictModel(value=2, text=冻结), DictModel(value=1, text=正常)]}
2020-11-07 08:54:24.084 [http-nio-8080-exec-2] INFO  org.jeecg.config.shiro.ShiroRealm:94 - ————————身份认证失败——————————IP地址:  10.240.121.155
2020-11-07 08:54:24.097 [http-nio-8080-exec-2] ERROR o.a.c.c.C.[.[.[/xtbg].[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/xtbg] threw exception [org.apache.shiro.authc.AuthenticationException: Token失效，请重新登录] with root cause
org.apache.shiro.authc.AuthenticationException: token为空!
	at org.jeecg.config.shiro.ShiroRealm.doGetAuthenticationInfo(ShiroRealm.java:95)
	at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:273)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:275)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260)
	at org.jeecg.config.shiro.filters.JwtFilter.executeLogin(JwtFilter.java:60)
	at org.jeecg.config.shiro.filters.JwtFilter.isAccessAllowed(JwtFilter.java:43)
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:214)
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:189)
	at org.jeecg.config.shiro.filters.JwtFilter.preHandle(JwtFilter.java:90)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code -1
`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你为什么不后台接口返回一个关键词，让前端根据关键词进行跳转

**Comment by onewaymail1** [comment]
谢谢，我见笑了
