### ISSUE TITLE
怎么弄热部署？ ##2.3版本添加spring-boot-devtools依赖，启动报错

### ISSUE THREAD

**Issue by Jianyi-He** [zhangdaiscott/jeecg-boot#1986]
##### 问题描述：
2.3版本添加spring-boot-devtools依赖，启动报错

##### 截图&代码：
1、在jeecg-boot-module-system的pom文件中加入spring-boot-devtools依赖
               <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>

2、启动报错：
   Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.system.api.ISysBaseAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1654)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1213)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)

3、应该是多模块代码类加载器不一致导致的。
4、在jeecg-boot-module-system的resource下新建文件/META-INF/spring-devtools.properties
      添加如下内容（此处尝试了N多次，怎么写才对...）：
      restart.include.projectcommon=/jeecg-system-local-api-[\\w-]+.jar

5、还是报错，找不到jeecg-system-local-api下的org.jeecg.common.system.api.ISysBaseAPI

6、不用spring-devtools你们用什么？改一点手动重启一下，蛋不疼吗？求教？！

**Comment by zhangdaiscott** [comment]
用jrbel
