### ISSUE TITLE
生成代码到模块后重新运行发生错误

### ISSUE THREAD

**Issue by ZCW223** [zhangdaiscott/jeecg-boot#2017]
##### 问题描述：在页面配置好表单生成代码到一个自己新建的模块后，在前端配好vue组件然后重新运行boot发生以下错误
该新建模块曾经有一次成功装配过生成的代码，
之前也有出现过同样错误，不过是换了一份备份的源码文件才解决的，
今天又出现这个bug就一定不是偶然问题，就想把它确定下来

##### 截图&代码：
错误提示。
![Uploading image.png…]()

2020-11-23 21:45:34.969 [main] INFO  org.jeecg.JeecgApplication:679 - The following profiles are active: dev
2020-11-23 21:45:37.329 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:557 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'cesOnlineContollerController' for bean class [org.jeecg.modules.demo.kjdemo.controller.CesOnlineContollerController] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.demo.CesOnlineContoller.controller.CesOnlineContollerController]
2020-11-23 21:45:37.333 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-23 21:45:37.345 [main] ERROR org.springframework.boot.SpringApplication:858 - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'cesOnlineContollerController' for bean class [org.jeecg.modules.demo.kjdemo.controller.CesOnlineContollerController] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.demo.CesOnlineContoller.controller.CesOnlineContollerController]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.jeecg.JeecgApplication.main(JeecgApplication.java:30)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'cesOnlineContollerController' for bean class [org.jeecg.modules.demo.kjdemo.controller.CesOnlineContollerController] conflicts with existing, non-compatible bean definition of same name and class [org.jeecg.modules.demo.CesOnlineContoller.controller.CesOnlineContollerController]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:348)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:286)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:287)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167)
	... 13 common frames omitted

Process finished with exit code 1

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
版本有点老了
