### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by tushaoang** [zhangdaiscott/jeecg-boot#2090]
##### 版本号：
2.4 版本 最后提交时间2020年12月8日 15:33:59

##### 问题描述：
上传图片后不能正常显示

##### 截图&代码：
位置：src/main/java/org/jeecg/common/util/CommonUtils.java
使用pinyin4j 中间件进行文件中文名转换时报错
![出错页面](https://user-images.githubusercontent.com/25601292/101573064-3f8e1d80-3a13-11eb-8cc9-2b9028466271.png)
![错误代码位置](https://user-images.githubusercontent.com/25601292/101573076-44eb6800-3a13-11eb-808b-9ab77514a134.png)

错误提示：

Caused by: java.lang.NoSuchMethodError: cn.hutool.core.lang.Singleton.get(Ljava/lang/String;Lcn/hutool/core/lang/func/Func0;)Ljava/lang/Object;
	at cn.hutool.extra.pinyin.engine.PinyinFactory.get(PinyinFactory.java:23)
	at cn.hutool.extra.pinyin.PinyinUtil.getEngine(PinyinUtil.java:21)
	at cn.hutool.extra.pinyin.PinyinUtil.getPinyin(PinyinUtil.java:52)
	at org.jeecg.common.util.CommonUtils.getFileName(CommonUtils.java:80)
	at org.jeecg.modules.system.controller.CommonController.uploadLocal(CommonController.java:134)
	at org.jeecg.modules.system.controller.CommonController.upload(CommonController.java:91)
	at org.jeecg.modules.system.controller.CommonController$$FastClassBySpringCGLIB$$669ac3eb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.jeecg.common.aspect.DictAspect.doAround(DictAspect.java:50)
	at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.jeecg.modules.system.controller.CommonController$$EnhancerBySpringCGLIB$$e057618c.upload(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	... 74 common frames omitted

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
帖错误异常

**Comment by tushaoang** [comment]
新增表单里面上传图片后显示缩略图正常，编辑和查看内容出现错误。

**Comment by tushaoang** [comment]
我把原来的代码修改为：
    try {
                fileName= PinyinHelper.toHanYuPinyinString(fileName, new HanyuPinyinOutputFormat(),StrUtil.EMPTY,true);
            } catch (BadHanyuPinyinOutputFormatCombination badHanyuPinyinOutputFormatCombination) {
                badHanyuPinyinOutputFormatCombination.printStackTrace();
            }
正常了。

**Comment by zhangdaiscott** [comment]
没重现，是不是你的hutool 版本号不对
