### ISSUE TITLE
online表单开发同步数据库提示错误

### ISSUE THREAD

**Issue by freewind1977** [zhangdaiscott/jeecg-boot#2126]
##### 截图&代码：
前端提示信息：同步数据库失败，Unable to perform unmarshalling at line number 0 and column 0. Message: null : origin(null)

后台异常：
```xml
<hibernate-mapping> 
   <class name="abcd" table="abcd" optimistic-lock="version"> 
    <id name="id" type="java.lang.String" length="36" unsaved-value="null"> 
     <generator class="uuid" /> 
    </id> 
    <property name="create_by" type="java.lang.String" access="property"> 
     <column name="create_by" length="50" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
    <property name="create_time" type="java.util.Date" access="property"> 
     <column name="create_time" length="20" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
    <property name="update_by" type="java.lang.String" access="property"> 
     <column name="update_by" length="50" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
    <property name="update_time" type="java.util.Date" access="property"> 
     <column name="update_time" length="20" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
    <property name="sys_org_code" type="java.lang.String" access="property"> 
     <column name="sys_org_code" length="64" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
    <property name="test" type="java.lang.String" access="property"> 
     <column name="test" length="32" not-null="false" unique="false"> 
      <comment></comment> 
     </column> 
    </property> 
   </class> 
  </hibernate-mapping>
```
  
org.hibernate.boot.InvalidMappingException: Could not parse mapping document: null (INPUT_STREAM)
        at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:46)
        at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:38)
        at org.hibernate.boot.spi.XmlMappingBinderAccess.bind(XmlMappingBinderAccess.java:94)
        at org.hibernate.boot.MetadataSources.addInputStream(MetadataSources.java:401)
        at org.jeecg.modules.online.config.b.c.a(DbTableProcess.java:126)
.....

追问：
1.在线表单同步数据库生成的表是在jeecg-boot库中吗？能否自行配置目标数据库？
2.出现上面的问题后，再次使用同步数据库功能，提示"网络延迟...“，后online表单一直刷新。

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看常见问题贴
