### ISSUE TITLE
sys_gateway_route  这个表的字段 persist 

### ISSUE THREAD

**Issue by freedomme** [zhangdaiscott/jeecg-boot#2160]
##### 问题描述：
sys_gateway_route  这个表的字段 persist 在mysql数据库 好像是有问题.在启动系统时,报下面错误.不知道是不是用到了数据库保留关键字.请教如何修正这个问题

##### 截图&代码：

org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE ' at line 1
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE ' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE ' at line 1
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy131.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:173)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:78)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy168.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:279)
	at org.jeecg.modules.system.service.impl.SysGatewayRouteServiceImpl.addRoute2Redis(SysGatewayRouteServiceImpl.java:40)
	at org.jeecg.modules.system.service.impl.SysGatewayRouteServiceImpl$$FastClassBySpringCGLIB$$3a99db8a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.jeecg.modules.system.service.impl.SysGatewayRouteServiceImpl$$EnhancerBySpringCGLIB$$45c97873.addRoute2Redis(<generated>)
	at org.jeecg.modules.init.SystemInitListener.onApplicationEvent(SystemInitListener.java:29)
	at org.jeecg.modules.init.SystemInitListener.onApplicationEvent(SystemInitListener.java:16)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.jeecg.JeecgSystemApplication.main(JeecgSystemApplication.java:34)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE ' at line 1

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by freedomme** [comment]
在实体类中 注销这个字段后,的确可以正常启动了, 请大神看看 怎样修复这个问题?

**Comment by yuanxu-xsmy** [comment]
因为persist这个字段在MySQL8中是关键字，查询的时候需要做下处理，加上反引号``。在实体类中可以这样处理: 
![image](https://user-images.githubusercontent.com/76983819/103603047-902c6400-4f48-11eb-9e17-d035d6da19e1.png)

**Comment by freedomme** [comment]
@yuanxu-xsmy    感谢您的回复,的确是在mysql8.0 版本出的问题,不过, 在实体类该字段上面增加一个注释 @TableField(value = "persist") ,这种办法是无效的 , 还是前面错误. 还是请作者大神 选择一个全面解决办法
