### ISSUE TITLE
微服务版本同步数据库报null错误

### ISSUE THREAD

**Issue by liquanxy** [zhangdaiscott/jeecg-boot#2205]
##### 截图&代码：

![QQ图片20210117215948](https://user-images.githubusercontent.com/29604435/104845261-562b6c80-590f-11eb-8b6f-e94adfbd0a09.png)
       2021-01-17 21:44:38.419 [http-nio-7001-exec-5] ERROR org.jeecg.modules.online.cgform.b.a:554 - null
        java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Hashtable.putAll(Hashtable.java:524)
	at org.hibernate.boot.registry.StandardServiceRegistryBuilder.applySettings(StandardServiceRegistryBuilder.java:276)
	at org.jeecg.modules.online.config.b.c.a(DbTableProcess.java:122)
	at org.jeecg.modules.online.cgform.service.impl.d.doDbSynch(OnlCgformHeadServiceImpl.java:350)
	at org.jeecg.modules.online.cgform.service.impl.d$$FastClassBySpringCGLIB$$a1d6ff6b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$56b7b5aa.doDbSynch(<generated>)
	at org.jeecg.modules.online.cgform.b.a.h(OnlCgformApiController.java:551)
	at org.jeecg.modules.online.cgform.b.a$$FastClassBySpringCGLIB$$b709559.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg_database.properties 打包里面有吗

**Comment by liquanxy** [comment]
jar包没有解开看，不知道有没有打包进去，后来我启动单体工程，用单体工程同步数据是可以的，唯独微服务启动就不行，过了段时间，重新跑微服务，又可以了，这里有个建议，数据源可以就用总配置的数据源，不要读这个属性文件，就不会出现类似的问题
