### ISSUE TITLE
jar包部署centos报错

### ISSUE THREAD

**Issue by lch245298** [zhangdaiscott/jeecg-boot#2257]
##### 版本号：
2.4.2

##### 问题描述：
打包jar包部署到centos，执行打包命令的时候报错，说找不到java.lang.NoClassDefFoundError: org/jeecg/common/base/BaseMap
打包不报错，idea本地正常启动运行，部署的时候怎么找不到
打包执行parent-install  parent-package
parant pom dependency：
<dependency>
        <groupId>org.jeecgframework.boot</groupId>
        <artifactId>jeecg-boot-base-tools</artifactId>
        <version>${jeecgboot.version}</version>
  </dependency>
  
  <dependency>
        <groupId>org.jeecgframework.boot</groupId>
        <artifactId>jeecg-boot-base-core</artifactId>
        <version>${jeecgboot.version}</version>
  </dependency>
  
  <dependency>
        <groupId>org.jeecgframework.boot</groupId>
        <artifactId>jeecg-system-local-api</artifactId>
        <version>${jeecgboot.version}</version>
  </dependency>

system pom ：
		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>jeecg-system-local-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>jeecg-boot-starter-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>jeecg-boot-module-demo</artifactId>
			<version>${jeecgboot.version}</version>
		</dependency>
              <dependency>
                  <groupId>org.jeecgframework.boot</groupId>
                  <artifactId>jeecg-boot-module-foundation</artifactId>
                  <version>${jeecgboot.version}</version>
              </dependency>

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62693683/107113560-a9ebfe80-689a-11eb-99a0-5ec31aa7c26c.png)

Jeecg  Boot Version: 2.4.2
Spring Boot Version: 2.3.5.RELEASE (v2.3.5.RELEASE)

2021-02-06 16:40:18.747 [background-preinit] INFO  org.hibernate.validator.internal.util.Version:21 - HV000001: Hibernate Validator 6.1.6.Final
2021-02-06 16:40:18.855 [main] INFO  org.jeecg.JeecgSystemApplication:55 - Starting JeecgSystemApplication v2.4.2 on localhost.localdomain with PID 19250 (/root/jeecgb       ootmaster/jeecg-boot-module-system-2.4.2.jar started by root in /root/jeecgbootmaster)
2021-02-06 16:40:18.855 [main] INFO  org.jeecg.JeecgSystemApplication:655 - The following profiles are active: prod
2021-02-06 16:40:19.628 [background-preinit] WARN  o.s.h.converter.json.Jackson2ObjectMapperBuilder:127 - For Jackson Kotlin classes support please add "com.fasterxml.       jackson.module:jackson-module-kotlin" to the classpath
2021-02-06 16:40:21.394 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:249 - Multiple Spring Data modules found, entering strict repository configuration        mode!
2021-02-06 16:40:21.398 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:127 - Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2021-02-06 16:40:21.517 [main] INFO  o.s.d.r.config.RepositoryConfigurationDelegate:187 - Finished Spring Data repository scanning in 96ms. Found 0 Redis repository in       terfaces.
2021-02-06 16:40:22.009 [main] ERROR org.springframework.boot.SpringApplication:837 - Application run failed
java.lang.IllegalStateException: Unable to load cache item
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
        at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:572)
        at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:419)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:137)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:423)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:257)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:291)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:131)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.jeecg.JeecgSystemApplication.main(JeecgSystemApplication.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NoClassDefFoundError: org/jeecg/common/base/BaseMap
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.cglib.core.ReflectUtils.addAllMethods(ReflectUtils.java:451)
        at org.springframework.cglib.proxy.Enhancer.getMethods(Enhancer.java:635)
        at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:670)
        at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
        at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at org.springframework.cglib.core.ClassLoaderAwareGeneratorStrategy.generate(ClassLoaderAwareGeneratorStrategy.java:57)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358)
        at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:585)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        ... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jeecg.common.base.BaseMap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 45 common frames omitted

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lch245298** [comment]
我又先clean了一下，就好了。。。
