### ISSUE TITLE
在MYSQL8.0.15环境下运行报错

### ISSUE THREAD

**Issue by xuepingXu** [zhangdaiscott/jeecg-boot#2258]
##### 问题描述：在MYSQL8.0.15环境下运行报错，内容如下
2021-02-06 16:09:02.136 [main] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore:3503 - ClusterManager: Scanning for instance "TF100775PC1612505287555"'s failed in-progress jobs.
2021-02-06 16:09:02.150 [main] INFO  org.quartz.core.QuartzScheduler:547 - Scheduler MyScheduler_$_TF100775PC1612598937454 started.
2021-02-06 16:09:02.168 [main] INFO  org.jeecg.JeecgSystemApplication:61 - Started JeecgSystemApplication in 15.646 seconds (JVM running for 17.94)
2021-02-06 16:09:02.178 [main] INFO  org.jeecg.modules.init.SystemInitListener:27 -  服务已启动，准备初始化路由配置 ###################
2021-02-06 16:09:02.325 [main] ERROR druid.sql.Statement:149 - {conn-10005, pstmt-20010} execute error. SELECT  id,router_id,name,uri,predicates,filters,strip_prefix,retryable,persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE (status = ?)
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'persist,show_api,status,create_by,create_time  FROM sys_gateway_route 
 
 WHERE ' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
已经修复了，新版persist关键词冲突的问题
