### ISSUE TITLE
online 报表开发，sql解析不出来

### ISSUE THREAD

**Issue by qianlei0007** [zhangdaiscott/jeecg-boot#2269]
2.4.2 版本号： mysql5.7
 问题描述： online 报表， 
##### 截图&代码：
2021-02-10 11:54:20.918 [http-nio-8080-exec-10] [31mWARN [0;39m [36mcom.alibaba.druid.pool.DruidDataSource:1414[0;39m - get connection timeout retry : 1
2021-02-10 11:55:20.921 [http-nio-8080-exec-10] [1;31mERROR[0;39m [36morg.jeecg.modules.online.cgreport.a.b:111[0;39m - Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 8, creating 0, createErrorCount 1
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 8, creating 0, createErrorCount 1
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:490)
	at org.jeecg.common.util.dynamic.db.DynamicDBUtil.findList(DynamicDBUtil.java:216)
===============================================================
CREATE TABLE `mp_person_info` (
	`id` VARCHAR(32) NOT NULL COMMENT '主键唯一编码',
	`person_type` INT NULL DEFAULT NULL COMMENT '类别',
	`person_type_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '人别name',
	`name` VARCHAR(32) NULL DEFAULT NULL COMMENT '名',
	`idcard` VARCHAR(32) NULL DEFAULT NULL COMMENT '身号',
	`former_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '用名',
	`sex` INT NULL DEFAULT NULL COMMENT '别',
	`sex_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '性name',
	`national` INT NULL DEFAULT NULL COMMENT '族',
	`national_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '族name',
	`birthday` VARCHAR(16) NULL DEFAULT NULL COMMENT '出生日期',
	`age` INT NULL DEFAULT NULL COMMENT '年龄',
	`body_height` INT NULL DEFAULT NULL COMMENT '身高',
	`body_size` INT NULL DEFAULT NULL COMMENT '体型',
	`body_size_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '体型name',
	`face_shape` INT NULL DEFAULT NULL COMMENT '脸型',
	`face_shape_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '脸型name',
	`blood_type` INT NULL DEFAULT NULL COMMENT '血型',
	`blood_type_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '血型name',
	`phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '联系方式',
	`education_level` INT NULL DEFAULT NULL COMMENT '文化程度',
	`education_level_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '文化程度name',
	`politics_status` INT NULL DEFAULT NULL COMMENT '政治面貌',
	`politics_status_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '政治面貌name',
	`join_party_time` DATETIME NULL DEFAULT NULL COMMENT '入党时间',
	`marital_status` INT NULL DEFAULT NULL COMMENT '婚姻状况',
	`marital_status_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '婚姻状况name',
	`marital_card_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '婚证编码',
	`marital_issuance_date` VARCHAR(20) NULL DEFAULT NULL COMMENT '签发日期',
	`have_child_number` INT NULL DEFAULT NULL COMMENT '现有子女数',
	`have_child_number_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '现有子女数name',
	`examination_certificate_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '婚育证编号',
	`child_is_have_vaccination` INT NULL DEFAULT NULL COMMENT '儿童是否预防接种',
	`child_is_have_vaccination_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '儿童是否预防接种name',
	`is_school_age_child` INT NULL DEFAULT NULL COMMENT '是否为学龄儿童',
	`is_school_age_child_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否为学龄儿童name',
	`is_go_school` INT NULL DEFAULT NULL COMMENT '是否就学',
	`is_go_school_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否就学name',
	`school_class_name` VARCHAR(32) NULL DEFAULT NULL COMMENT '学校名称与班级',
	`birth_control_measures` INT NULL DEFAULT NULL COMMENT '节育措施',
	`birth_control_measures_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '节育措施name',
	`door_number` VARCHAR(32) NULL DEFAULT NULL COMMENT '户号',
	`door_relation` INT NULL DEFAULT NULL COMMENT '与户主关系',
	`door_relation_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '与户主关系name',
	`door_nature` INT NULL DEFAULT NULL COMMENT '户籍性质',
	`door_nature_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '户籍性质name',
	`door_address` INT NULL DEFAULT NULL COMMENT '户籍地址',
	`door_address_value` VARCHAR(255) NULL DEFAULT NULL COMMENT '户籍地址name',
	`door_address_detail` VARCHAR(255) NULL DEFAULT NULL COMMENT '户籍详址',
	`live_address_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '现有住址/房屋地址id',
	`live_address` VARCHAR(255) NULL DEFAULT NULL COMMENT '现有住址/房屋地址',
	`professional` VARCHAR(32) NULL DEFAULT NULL COMMENT '职业',
	`work_unit` VARCHAR(32) NULL DEFAULT NULL COMMENT '工作单位',
	`work_address` VARCHAR(32) NULL DEFAULT NULL COMMENT '工作地址',
	`work_address_id` VARCHAR(64) NULL DEFAULT NULL COMMENT '工作地址id',
	`income_situation` INT NULL DEFAULT NULL COMMENT '收入情况',
	`income_situation_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '收入情况name',
	`is_have_animal` INT NULL DEFAULT NULL COMMENT '是否养宠物',
	`is_have_animal_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否养宠物name',
	`animal_varieties` VARCHAR(20) NULL DEFAULT NULL COMMENT '宠物品种',
	`animal_size` INT NULL DEFAULT NULL COMMENT '宠物大小',
	`animal_size_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '宠物大小name',
	`person_category` INT NULL DEFAULT NULL COMMENT '流口/常住',
	`person_category_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '流口/常住name',
	`is_have_religious` INT NULL DEFAULT NULL COMMENT '是否有',
	`is_have_religious_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否有',
	`is_have_civil_affair` INT NULL DEFAULT NULL COMMENT '是否持有护照',
	`is_have_civil_affair_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否持有护照name',
	`is_fourteen_back_urumqi` INT NULL DEFAULT NULL COMMENT '是否是14日内来',
	`is_fourteen_back_urumqi_value` VARCHAR(64) NULL DEFAULT NULL COMMENT '是否是14日内来乌',
	`photo_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '照片',
	PRIMARY KEY (`id`) USING BTREE
)
COMMENT='人员基本信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DYNAMIC
;

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你这个是数据库连接失败吧，帖处理的错误日志不够分析，多帖一些
