### ISSUE TITLE
新建模块问题

### ISSUE THREAD

**Issue by Zhangdeli1993** [zhangdaiscott/jeecg-boot#2331]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/22495072/110101782-f6b1ef00-7dde-11eb-9d77-641f3fc08189.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
扫码路径配置了吗

**Comment by Zhangdeli1993** [comment]
> 扫码路径配置了吗

扫码路径配置了2处
1.启动器位置
![image](https://user-images.githubusercontent.com/22495072/110266244-5a633480-7ff8-11eb-91e9-0f50ada3976f.png)
2.mybatis配置处
![image](https://user-images.githubusercontent.com/22495072/110266318-79fa5d00-7ff8-11eb-80d0-74f0bf292038.png)

**Comment by Zhangdeli1993** [comment]
问题已解决.
除了以上2处需要添加扫包路径外还需在MybatisPlusConfig配置
![image](https://user-images.githubusercontent.com/22495072/110281794-534c1e80-8018-11eb-92e5-08738cd05d1c.png)

**Comment by zuiko1** [comment]
> 问题已解决. 除了以上2处需要添加扫包路径外还需在MybatisPlusConfig配置 ![image](https://user-images.githubusercontent.com/22495072/110281794-534c1e80-8018-11eb-92e5-08738cd05d1c.png)

对我也是碰到了这个问题 我用的mybatis写的xml扫不出来 要改mybatis-plus下的类路径

**Comment by jiangxiaohui1** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-07-09 03:45:39.054 [main] ERROR org.springframework.boot.SpringApplication:818 - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgSystemApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/jeecg/common/util/security/AbstractQueryBlackListHandler.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:756)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:572)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at org.jeecg.JeecgSystemApplication.main(JeecgSystemApplication.java:30)
Caused by: java.io.FileNotFoundException: class path resource [org/jeecg/common/util/security/AbstractQueryBlackListHandler.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:203)
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:699)
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:1013)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:340)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:198)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:303)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
	... 13 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:13096', transport: 'socket'
