### ISSUE TITLE
Auto-poi，使用模板导出excel模板时功能，提示找不到模板文件

### ISSUE THREAD

**Issue by 793292556** [zhangdaiscott/jeecg-boot#2477]
##### 版本号：

2.4.3
2.4.2手动覆盖升级到的2.4.3
##### 问题描述：
windown系统，idea编译时，模板文件放在”D:/opt/temple/mysteelOutput.xlsx“
执行excel模板导出时，提示找不到模板文件

##### 截图&代码：
2021-04-16 20:39:45.494 [http-nio-9998-exec-3] ERROR org.jeecgframework.poi.cache.ExcelCache:89 - class path resource [D:/opt/temple/mysteelOutput.xlsx] cannot be opened because it does not exist
java.io.FileNotFoundException: class path resource [D:/opt/temple/mysteelOutput.xlsx] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.jeecgframework.poi.cache.ExcelCache.getWorkbookByTemplate(ExcelCache.java:75)
	at org.jeecgframework.poi.excel.export.template.ExcelExportOfTemplateUtil.getCloneWorkBook(ExcelExportOfTemplateUtil.java:203)
	at org.jeecgframework.poi.excel.export.template.ExcelExportOfTemplateUtil.createExcleByTemplate(ExcelExportOfTemplateUtil.java:167)
	at org.jeecgframework.poi.excel.ExcelExportUtil.exportExcel(ExcelExportUtil.java:169)
	at org.jeecg.modules.spider.webPrice.controller.AddResutlFile.execute(AddResutlFile.java:107)

调试在
 public InputStream getInputStream() throws IOException {}抛异常，

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by 793292556** [comment]
升级下poi到 1.3，找不到模板问题有时候能解决，但是有几个bug，

为map中key的值为”textWuliaoDami“，这种时，模板中对应键值为”text_wuliao_dami“名时，使用map.putall(),将map添加进去，系统会将key值填写到模板中，而不是填写map的value值；

 Map<String, Object> resultmap = new HashMap<>();
                        resultmap.put("title", GetFormatTimes("MM月dd日"));
                        //解析对象生成map
                        if (null != objToMap(webpriceResult)) {
                            Map<String, String> map = objToMap(webpriceResult);//用fastjason 将对象转为map
                             resultmap.putAll(objToMap(map));

如果用map.foreach循环添加进去，系统会报错找不到模板文件……
//                          
//                            map.forEach((k, v) -> resultmap.put(k, v));
                            System.out.println("当日价格map：" + objToMap(webpriceResult));
                        
                        }
