### ISSUE TITLE
java.lang.ClassNotFoundException: io.swagger.models.Contact

### ISSUE THREAD

**Issue by TorGor** [zhangdaiscott/jeecg-boot#255]
##### 截图&代码：

```
2019-07-02 10:52:13.353 [main] ERROR org.springframework.boot.SpringApplication:858 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceModelToSwagger2MapperImpl': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:265)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1253)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1168)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.jeecg.JeecgApplication.main(JeecgApplication.java:23)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:583)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:568)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248)
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/swagger/models/Contact
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:668)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.swagger.models.Contact
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 common frames omitted
```

**Comment by galaxist** [comment]
是你依赖冲突啦

**Comment by TorGor** [comment]
> 是你依赖冲突啦

可是我没有改过任何依赖啊

**Comment by TorGor** [comment]
> 是你依赖冲突啦

可是，我没有改过任何依赖啊

**Comment by TorGor** [comment]
> 是你依赖冲突啦

@galaxist 我是直接 clone 启动，并没有自行添加任何依赖啊。

**Comment by zhangdaiscott** [comment]
详细说明你的部署环境

**Comment by galaxist** [comment]
这个还要看下你maven的本地私服是不是都下载好jar了

**Comment by TorGor** [comment]
> 这个还要看下你maven的本地私服是不是都下载好jar了

@galaxist  是的，本地仓库检查过，已经存在需要的 jar ，我的私服 nexus 应该不影响才对吧。

**Comment by TorGor** [comment]
> 详细说明你的部署环境

@zhangdaiscott  

*  IntelliJ IDEA 2018.1.2 x64
* Maven home: E:\Program File\Maven\apache-maven-3.5.2
* Java version: 1.8.0_151, vendor: Oracle Corporation

**Comment by TorGor** [comment]
### 我现在的解决方式:
* change swagger2 version <springfox-swagger2>2.9.0</springfox-swagger2>
* remove dependency  springfox-bean-validators
![image](https://user-images.githubusercontent.com/26076851/60500761-7a076d00-9ced-11e9-975c-4b17163ba7a3.png)

现在可以正常访问 swagger 了
![image](https://user-images.githubusercontent.com/26076851/60499843-d10c4280-9ceb-11e9-8b82-1bda466a22c1.png)

**Comment by zhangdaiscott** [comment]
你这个问题，我们没遇到过
