### ISSUE TITLE
连接SQL Server报错：该驱动程序不支持 SQL Server 8 版

### ISSUE THREAD

**Issue by ddwolf715** [zhangdaiscott/jeecg-boot#2620]
##### 版本号：
v2.4.3

##### 问题描述：
在线开发--》多数据源管理--》新一个连接SQL Server的信息。
连接的SQL Server版本是2000版（客户业务系统的生产库），jeecg-boot最低支持什么版本的SQL Server？低版本的SQL Server要怎么样连接才可以？

报错信息如下（见截图）：
连接失败
数据库连接失败：该驱动程序不支持 SQL Server 8 版。 ClientConnectionId:8bffc6e7-9434-4524-acae-758bec5faf16

补充：
连接的源确定是无问题的，用Navicat (第三方客户端)连接是正常的。

##### 截图&代码：
<img width="1124" alt="问题截图" src="https://user-images.githubusercontent.com/17849555/120409727-25ab1300-c384-11eb-8154-5135f5c432bb.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
换下驱动试试，默认支持的是SqlServer 2017

**Comment by ddwolf715** [comment]
jdbc 版本降级？

**Comment by ddwolf715** [comment]
我添加了 jTDS 的驱动，改了一下驱动类和URL，数据源配置的地方测试是通过了，但onlien报表又运行SQL出错，配置数据源通过了，报表使用数据源也不一定是可用的？是这样吗？或者怎么添加和配置非jeecg-boot自带驱动之除的驱动程序？

后端报出错误如下，看错误信息，似乎连接池是创建成功了：
2021-06-02 11:17:18.476 [http-nio-8035-exec-2] INFO  org.jeecg.modules.online.cgreport.service.a.b:167 - 【Online多数据源逻辑】报表查询参数params: {"_t":"","pageNo":"1","pageSize":"10"}
2021-06-02 11:17:18.594 [http-nio-8035-exec-2] INFO  org.jeecg.common.system.query.QueryGenerator:989 - query auth sql is = 
2021-06-02 11:17:18.599 [http-nio-8035-exec-2] INFO  org.jeecg.modules.online.cgreport.service.a.b:226 - 多数据源 报表查询sql=>querySql: select * from (select id1 From test_table1) jeecg_rp_temp  where 1=1 
2021-06-02 11:17:18.599 [http-nio-8035-exec-2] INFO  org.jeecg.modules.online.cgreport.service.a.b:227 - 多数据源 报表查询sql=>pageSQL: select * from ( select row_number() over(order by tempColumn) tempRowNumber, * from (select top 10 tempColumn = 0,  * from (select id1 From test_table1) jeecg_rp_temp  where 1=1 ) t ) tt where tempRowNumber > 0
2021-06-02 11:17:18.600 [http-nio-8035-exec-2] INFO  org.jeecg.modules.online.cgreport.service.a.b:228 - 多数据源 报表查询sql=>countSql: SELECT COUNT(1) "total" FROM ( select * from (select id1 From test_table1) jeecg_rp_temp  where 1=1  ) temp_count
2021-06-02 11:17:23.780 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:55 - ******************************************
2021-06-02 11:17:23.782 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:56 - *                                        *
2021-06-02 11:17:23.783 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:57 - *====【ins_MSSQL】=====Druid连接池已启用 ====*
2021-06-02 11:17:23.783 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:58 - *                                        *
2021-06-02 11:17:23.784 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:59 - ******************************************
2021-06-02 11:17:23.784 [http-nio-8035-exec-2] INFO  org.jeecg.common.util.dynamic.db.DynamicDBUtil:84 - --------getDbSourceBydbKey------------------创建DB数据库连接-------------------
2021-06-02 11:17:25.499 [http-nio-8035-exec-2] INFO  com.alibaba.druid.pool.DruidDataSource:994 - {dataSource-2} inited
2021-06-02 11:17:25.752 [Druid-ConnectionPool-Create-1103338154] ERROR com.alibaba.druid.pool.DruidDataSource:2781 - create connection SQLException, url: jdbc:jtds:sqlserver://localhost:1433;SelectMethod=cursor;DatabaseName=SSMISDIYDB, errorCode 0, state HY000
java.sql.SQLException: The SQL statement must not be null or empty.
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeImpl(JtdsStatement.java:757)
	at net.sourceforge.jtds.jdbc.JtdsStatement.execute(JtdsStatement.java:1282)
	at com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker.isValidConnection(MSSQLValidConnectionChecker.java:50)
	at com.alibaba.druid.pool.DruidAbstractDataSource.validateConnection(DruidAbstractDataSource.java:1386)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1720)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2779)
2021-06-02 11:17:25.755 [Druid-ConnectionPool-Create-1103338154] INFO  com.alibaba.druid.pool.DruidAbstractDataSource:1791 - {dataSource-2} failContinuous is true

我添加的maven如下

		<dependency>
			<groupId>net.sourceforge.jtds</groupId>
			<artifactId>jtds</artifactId>
			<version>1.3.1</version>
			<scope>runtime</scope>
		</dependency>
