### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by ProwDong** [zhangdaiscott/jeecg-boot#2642]
##### 版本号：
2.4.3

##### 问题描述：
在服务上启动后，会出现”远程主机强迫关闭了一个现有的连接。"错误，但是程序本身并不受什么影响，可以正常访问。请问这个是什么情况，没有查到解决办法。这种情况因为mysql的配置有问题么？

##### 截图&代码：

`2021-06-07 18:44:26.055 [lettuce-nioEventLoop-4-5] [34mINFO [0;39m [36mio.let
tuce.core.protocol.CommandHandler:217[0;39m - null Unexpected exception during
request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketCha
nnel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
EventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30)
        at java.lang.Thread.run(Unknown Source)

`

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
这个问题我也比较常见，我觉得应该是浏览器端或者终端与服务端断开连接导致的，而不是和数据库。
