### ISSUE TITLE
生成微服务模块后无法登录

### ISSUE THREAD

**Issue by ordinaryworlds** [zhangdaiscott/jeecg-boot#2712]
##### 截图&代码：
feign.FeignException$NotFound: [404] during [GET] to [http://jeecg-system/sys/api/getUserByName?username=admin] [ISysBaseAPI#getUserByName(String)]: [<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} ... (682 bytes)]
	at feign.FeignException.clientErrorStatus(FeignException.java:201) ~[feign-core-10.10.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:177) ~[feign-core-10.10.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.10.1.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.10.1.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.10.1.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.10.1.jar:na]

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看看版本号匹配吗
