### ISSUE TITLE
org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到

### ISSUE THREAD

**Issue by spe-show** [zhangdaiscott/jeecg-boot#2717]
##### 版本号：
2.4.3及以上，jdk1.8, tomcat9

##### 问题描述：
这个问题在8.5.63版本没有问题，tomcat升级到更高版本就会出现。

##### 截图&代码：
28-Jun-2021 17:23:06.665 严重 [http-nio-20099-exec-1] org.apache.coyote.AbstractProtocol$ConnectionHandler.process 读取请求时出错，忽略
	java.lang.IllegalArgumentException: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.WsSession.<init>(WsSession.java:278)
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:126)
		... 7 more
	Caused by: javax.naming.NameNotFoundException: 名称[org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到[org.jeecg.modules.message.websocket.WebSocket]。
		at org.apache.naming.NamingContext.lookup(NamingContext.java:840)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
		at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:583)
		at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:485)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:174)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
		at org.apache.tomcat.websocket.WsSession.<init>(WsSession.java:275)
		... 8 more
28-Jun-2021 17:23:06.665 严重 [http-nio-20099-exec-2] org.apache.coyote.AbstractProtocol$ConnectionHandler.process 读取请求时出错，忽略
	java.lang.IllegalArgumentException: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.WsSession.<init>(WsSession.java:278)
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:126)
		... 7 more
	Caused by: javax.naming.NameNotFoundException: 名称[org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到[org.jeecg.modules.message.websocket.WebSocket]。
		at org.apache.naming.NamingContext.lookup(NamingContext.java:840)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:172)
		at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:583)
		at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:485)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:174)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
		at org.apache.tomcat.websocket.WsSession.<init>(WsSession.java:275)
		... 8 more
28-Jun-2021 17:23:15.525 严重 [http-nio-20099-exec-3] org.apache.coyote.AbstractProtocol$ConnectionHandler.process 读取请求时出错，忽略
	java.lang.IllegalArgumentException: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: javax.websocket.DeploymentException: Endpoint instance creation failed
		at org.apache.tomcat.websocket.WsSession.<init>(WsSession.java:278)
		at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:126)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by spe-show** [comment]
have finished

**Comment by tinyXiongGG** [comment]
> have finished

你是怎么解决的呀，降了 tomcat 版本？

**Comment by spe-show** [comment]
嗯 是的 换了8.5.63的版本&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 上午9:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到 (#2717)





  
have finished
  
你是怎么解决的呀，降了 tomcat 版本？

**Comment by Benjamin-536** [comment]
> 嗯 是的 换了8.5.63的版本&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jeecgboot/jeecg-boot" ***@***.***&gt;; 发送时间:&nbsp;2021年7月12日(星期一) 上午9:44 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [jeecgboot/jeecg-boot] org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到 (#2717) have finished 你是怎么解决的呀，降了 tomcat 版本？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

将jeecgRedisClient交有Spring管理，注解更换成@Autowired

**Comment by steel-pot** [comment]
> > 嗯 是的 换了8.5.63的版本 
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "jeecgboot/jeecg-boot" _**@**_._**>; 发送时间: 2021年7月12日(星期一) 上午9:44 _**@**_.**_>; _**@**_._**>;"State _**@**_.**_>; 主题: Re: [jeecgboot/jeecg-boot] org.jeecg.modules.message.websocket.WebSocket/jeecgRedisClient]未在此上下文中绑定。找不到 (#2717) have finished 你是怎么解决的呀，降了 tomcat 版本？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 将jeecgRedisClient交有Spring管理，注解更换成@Autowired

必须感谢下,一直使用的jar包,但上面突然要求tomcat版本必须最新,然后就用tomcat,一样的tomcat版本,一样的java版本,一样的程序代码,在我本地正常,上服务器就是不正常,人都折腾晕了,还好发现了这个,将注解改成@Autowired就行了org.jeecg.modules.message.websocket.WebSocket
