### ISSUE TITLE
v2.4.5, Sql版本不一致问题

### ISSUE THREAD

**Issue by youkale** [zhangdaiscott/jeecg-boot#3135]
##### 版本号：
v2.4.5

##### 问题描述：
根据教程配置数据库、redis配置后，导入jeecgboot-mysql-5.7.sql，tables_xxl_job.sql，后启动报错，尝试通过导入2.4.3->2.4.5 的sql脚本，数据提示字段重复

##### 截图&代码：
mysql 
```
(1060, "Duplicate column name 'auth_mode'")
```

spring-boot
```
2021-10-26 14:53:17.166 [main] ERROR druid.sql.Statement:149 - {conn-10005, pstmt-20002} execute error. SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = ? FOR UPDATE
java.sql.SQLSyntaxErrorException: Table 'jeecg-boot.QRTZ_LOCKS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3240)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3237)
```

通过上面观察，基本上确定是表结构改动的问题。 建议加入 `flyway` 通过改框架管理sql变更的问题。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liudonghua123** [comment]
我也遇到类似的，只能重新初始化数据库

![0cc1e2fef0a3f2d4e0bba7a9b0a21cee](https://user-images.githubusercontent.com/2276718/218946402-c631e94b-6853-4de8-ba6f-17b6873b5fb2.jpg)

https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
https://www.thegeekdiary.com/changing-the-value-of-lower_case_table_names-in-mysql-8/

1. backup
```
mysqldump -A > mysql.sql
cp -r /var/lib/mysql /var/lib/mysql.backup
```
2. stop
```
service mysql stop
service mysql status
```
3. cleanup data dir of mysql
```
rm -rf /var/lib/mysql/*
```
4. change configs in /etc/mysql/mysql.conf.d/mysqld.cnf
```
add lower_case_table_names = 1 in [mysqld]
```
4. reinitialize
```
mysqld --initialize
```
5. found the root password
```
cat /var/log/mysql/error.log|grep password
```
6. restore data
```
mysql -u root -p
source mysql.sql
# WHY? grants are lost, need to recreate
show grants for 'device_reservation'@'%';
grant all privileges on device_reservation.* to 'device_reservation'@'%';
```
