### ISSUE TITLE
出现可能因为定时器线程池的原因导致内存溢出项目down掉的问题

### ISSUE THREAD

**Issue by 343122875** [zhangdaiscott/jeecg-boot#355]
##### 版本号：
jeecg-boot 2.0.2
mysql 5.7

##### 问题描述：
今早前端出现接口6s超时，发现后端项目down掉，查看日志发现最后一条正常后的异常为java.lang.OutOfMemoryError: Java heap space，且定时任务查询报错，项目未上线，基本就是定时任务在执行。机子为16c8g。

##### 截图&代码：
2019-07-26 10:06:14.409 [http-nio-8111-exec-16] WARN  org.apache.shiro.authc.AbstractAuthenticator:216 - Authentication failed for token submission [org.jeecg.modules.shiro.authc.JwtToken@6a9ef1e6].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:08:16.894 [QuartzScheduler_quartzScheduler-NON_CLUSTERED_MisfireHandler] ERROR druid.sql.Statement:149 - {conn-10103, pstmt-21388} execute error. SELECT COUNT(TRIGGER_NAME) FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'quartzScheduler' AND NOT (MISFIRE_INSTR = -1) AND NEXT_FIRE_TIME < ? AND TRIGGER_STATE = ?
java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:10:33.992 [http-nio-8111-exec-17] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet]:175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/matrix-platform] threw exception [Filtered request failed.] with root cause
java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:09:36.130 [Catalina-utility-1] ERROR org.apache.coyote.http11.Http11NioProtocol:175 - Error processing async timeouts
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:586)
	at org.apache.coyote.AbstractProtocol$1.run(AbstractProtocol.java:574)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:10:33.992 [http-nio-8111-exec-11] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:83 - Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1053)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:348)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:173)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:11:06.417 [QuartzScheduler_quartzScheduler-NON_CLUSTERED_MisfireHandler] ERROR com.alibaba.druid.pool.DruidDataSource:1777 - discard connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4534)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:714)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:414)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:399)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy299.rollback(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3712)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3258)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018)
Caused by: java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:11:06.418 [QuartzScheduler_quartzScheduler-NON_CLUSTERED_MisfireHandler] ERROR o.s.scheduling.quartz.LocalDataSourceJobStore:3714 - Couldn't rollback jdbc connection. No operations allowed after connection closed.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4534)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:714)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:414)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:399)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy299.rollback(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3712)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3258)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018)
Caused by: java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:11:13.529 [QuartzScheduler_quartzScheduler-NON_CLUSTERED_MisfireHandler] WARN  o.q.i.j.AttributeRestoringConnectionInvocationHandler:144 - Failed restore connection's original auto commit setting.
java.sql.SQLException: connection disabled
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1163)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1148)
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:701)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:141)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3662)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3268)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4534)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:714)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.logging.LogFilter.connection_rollback(LogFilter.java:414)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.FilterAdapter.connection_rollback(FilterAdapter.java:974)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.filter.stat.StatFilter.connection_rollback(StatFilter.java:275)
	at com.alibaba.druid.filter.FilterChainImpl.connection_rollback(FilterChainImpl.java:709)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.rollback(ConnectionProxyImpl.java:399)
	at com.alibaba.druid.pool.DruidPooledConnection.rollback(DruidPooledConnection.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy299.rollback(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3712)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3258)
	... 2 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
2019-07-26 10:11:09.753 [quartzScheduler_QuartzSchedulerThread] ERROR com.alibaba.druid.pool.DruidDataSource:1777 - discard connection
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1559)
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:199)
	at com.alibaba.druid.filter.FilterAdapter.connection_commit(FilterAdapter.java:782)
	at com.alibaba.druid.filter.logging.LogFilter.connection_commit(LogFilter.java:433)
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:194)
	at com.alibaba.druid.filter.FilterAdapter.connection_commit(FilterAdapter.java:782)
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:194)
	at com.alibaba.druid.filter.stat.StatFilter.connection_commit(StatFilter.java:267)
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:194)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.commit(ConnectionProxyImpl.java:122)
	at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:749)
	at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy299.commit(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.commitConnection(JobStoreSupport.java:3732)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3851)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)

**Comment by zhangdaiscott** [comment]
是你们自己的测试环境吗？ 
可以在定时任务里面打点日志，看看是不是定时任务的问题。

**Comment by 343122875** [comment]
> 是你们自己的测试环境吗？
> 可以在定时任务里面打点日志，看看是不是定时任务的问题。

暂时没分测试、正式，算是正式环境吧，后面会直接用这台linux，这个异常今天第一次出现，我先打log观察下

**Comment by zhangdaiscott** [comment]
ok

**Comment by wangliguokaka** [comment]
我也遇到找个问题了，最好排查出来是什么原因了吗？
