### ISSUE TITLE
compilation.templatesPlugin is not a function

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#371]
##### 版本号：
2.0.2

##### 问题描述：
前端代码 npm install 成功之后，npm run serve 出现 `compilation.templatesPlugin is not a function` 错误

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2276718/62281935-3d13cf00-b481-11e9-8a44-3feda1f821ac.png)

**Comment by techeaven** [comment]
用yarn install 试试，前提是先通过命令```npm install -g yarn```安装yarn

**Comment by liudonghua123** [comment]
@yarn
我用yarn安装一直不成功，之前都是可以的

```
:\code\java\jboot_jm\ant-design-vue-jeecg>yarn
yarn install v1.17.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning vue-photo-preview > autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
warning vue-photo-preview > extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
warning vue-photo-preview > vue-loader > postcss-selector-parser > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
warning vue-photo-preview > autoprefixer-loader > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning vue-photo-preview > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning vue-photo-preview > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @babel/polyfill@7.4.4: ???? As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
warning @vue/cli-plugin-eslint > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue-loader@15.7.1" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.7.1" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
warning " > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] Building fresh packages...
[5/5] ⠐ ant-design-vue
[-/5] ⠐ waiting...
[3/5] ⠐ yorkie
[4/5] ⠐ node-sass
error D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.0.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.0.0
gyp verb command install [ '12.0.0' ]
gyp verb install input version string "12.0.0"
gyp verb install installing version: 12.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.0.0
gyp verb build dir attempting to create "build" dir: D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Liu.D.H\\.node-gyp\\12.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Liu.D.H\\.node-gyp\\12.0.0',
gyp info spawn args   '-Dnode_gyp_dir=D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Liu.D.H\\.node-gyp\\12.0.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Liu.D.H\.node-gyp\12.0.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:431:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:83:17)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\code\\java\\jboot_jm\\ant-design-vue-jeecg\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.





D:\code\java\jboot_jm\ant-design-vue-jeecg>npm rebuild node-sass

> node-sass@4.12.0 install D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Liu.D.H\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-72_binding.node

> node-sass@4.12.0 postinstall D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass
> node scripts/build.js

Binary found at D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass\vendor\win32-x64-72\binding.node
Testing binary
Binary is fine
node-sass@4.12.0 D:\code\java\jboot_jm\ant-design-vue-jeecg\node_modules\node-sass

D:\code\java\jboot_jm\ant-design-vue-jeecg>
```

**Comment by zhangdaiscott** [comment]
常见问题贴里面有，遇到问题请先看常见问题贴
http://www.jeecg.org/forum.php?mod=viewthread&tid=7816&extra=page%3D1

**Comment by jzyds** [comment]
npm i --save-dev html-webpack-plugin@next

**Comment by pitthehan** [comment]
> npm i --save-dev html-webpack-plugin@next

You made my day
