### ISSUE TITLE
建议提供codegenerate的源码，方便调试问题

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeecg-boot#46]
你好，在代码自动生成这块抛出的异常，通过异常堆栈信息看不到错误原因，非常难调试，因为mvnrepository没有提供相应的源码包，即使设置了断点，混淆后的代码也看不到相关上下文变量内容，例如下面的错误，希望可以mvn上传`codegenerate`的时候也把源码包一起上传

```
......
13:43:27.572 [main] DEBUG org.jeecgframework.codegenerate.generate.impl.a.a - [generate]	 template:java\${bussiPackage}\${entityPackage}\vue\modules\${entityName}Modal.vuei ==> D:/code/java/jeecg-boot/jeecg-boot\src/main/java\org\jeecg\modules\jmwx\vue\modules\MmSetmealBaseModal.vue
[not-generate] WARN: test expression is null by key:[Drawer.vuei] on template:[java\${bussiPackage}\${entityPackage}\vue\modules\${entityName}Modal__Style@Drawer.vuei]
java.lang.NullPointerException
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:68)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:55)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:39)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:106)
	at org.jeecg.JeecgCodeGenerator.main(JeecgCodeGenerator.java:53)
13:43:27.582 [main] DEBUG org.jeecgframework.codegenerate.generate.impl.a.a - -------templateRootDir--D:\code\java\jeecg-boot\jeecg-boot\target\classes\jeecg\code-template\one
13:43:27.582 [main] DEBUG org.jeecgframework.codegenerate.generate.impl.a.a - -------srcFile--D:\code\java\jeecg-boot\jeecg-boot\target\classes\jeecg\code-template\one\java\${bussiPackage}\${entityPackage}\vue\modules\${entityName}Modal__Style@Drawer.vuei
13:43:27.582 [main] DEBUG org.jeecgframework.codegenerate.generate.impl.a.a - -------templateFile--java\${bussiPackage}\${entityPackage}\vue\modules\${entityName}Modal__Style@Drawer.vuei
13:43:27.582 [main] DEBUG org.jeecgframework.codegenerate.generate.impl.a.a - -------outputFilepath--null
13:43:27.582 [main] ERROR org.jeecgframework.codegenerate.generate.impl.a.a - java.lang.NullPointerException
13:43:27.582 [main] DEBUG org.jeecgframework.codegenerate.generate.a.a - -------classpath-------/D:/code/java/jeecg-boot/jeecg-boot/target/classes/jeecg/code-template/one
13:43:27.582 [main] INFO org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne - ----jeecg----Code----Generation-----[单表模型：mm_setmeal_base]------ 生成完成。。。
----jeecg--------- Code------------- Generation -----[单表模型]------- 生成完成。。。
......

Process finished with exit code 0
```

![image](https://user-images.githubusercontent.com/2276718/56109998-6ddd0080-5f85-11e9-91ab-f0cb8448bec8.png)

**Comment by liudonghua123** [comment]
查看了混淆后的代码，看了两小时也没发现是什么问题，没有源码调试太困难了，无法判断是什么地方出什么错

**Comment by galaxist** [comment]
配置有问题，我遇到过的空值原因是配置的数据库连接有误。

**Comment by liudonghua123** [comment]
@galaxist 我仔细检查了一下，数据库连接没有问题，否则就不会生成部分代码了，而是全部都不会生成了

**Comment by zhangdaiscott** [comment]
java\${bussiPackage}\${entityPackage}\vue\modules\${entityName}Modal__Style@Drawer.vuei
这个文件删掉，你试试

**Comment by zhangdaiscott** [comment]
已经处理，先删除 }Modal__Style@Drawer.vuei 后缀文件
