### ISSUE TITLE
导出报异常

### ISSUE THREAD

**Issue by brade080710** [zhangdaiscott/jeecg-boot#478]
##### 版本号：
2.0.2

##### 问题描述：
导出功能后台报异常

##### 截图&代码：
 @RequestMapping(value = "/exportXls")
  public ModelAndView exportXls(HttpServletRequest request, HttpServletResponse response, GenerateQrcode generateQrcode) {
	  LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();
	  //--------------------------------------------------------------------------------
	  // Step.1 组装查询条件
	  QueryWrapper<GenerateQrcode> queryWrapper = QueryGenerator.initQueryWrapper(generateQrcode, request.getParameterMap());

	  // Step.2 AutoPoi 导出Excel
	  ModelAndView mv = new ModelAndView(new JeecgEntityExcelView());
	  List<GenerateQrcode> pageList = generateQrcodeService.list(queryWrapper);
	  // 导出文件名称
	  mv.addObject(NormalExcelConstants.FILE_NAME, "专属经纪人列表"); //此处设置的filename无效 ,前端会重更新设置一下
	  mv.addObject(NormalExcelConstants.CLASS, generateQrcode.getClass());
	  mv.addObject(NormalExcelConstants.PARAMS, new ExportParams( "专属经纪人列表数据", "导出人:"+sysUser.getRealname(),  "导出信息"));
	  mv.addObject(NormalExcelConstants.DATA_LIST, pageList);
	  return mv;

异常信息：
2019-08-29 11:55:41.499 ERROR org.jeecgframework.poi.excel.export.ExcelExportServer Line:171 - null
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45009)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45012)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jeecgframework.poi.excel.export.ExcelExportServer.createSheet(ExcelExportServer.java:125)
	at org.jeecgframework.poi.excel.ExcelExportUtil.exportExcel(ExcelExportUtil.java:64)
	at org.jeecgframework.poi.excel.view.JeecgEntityExcelView.renderMergedOutputModel(JeecgEntityExcelView.java:61)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(S)V
	at org.jeecgframework.poi.excel.export.styler.ExcelExportStylerDefaultImpl.stringNoneStyle(ExcelExportStylerDefaultImpl.java:69)
	at org.jeecgframework.poi.excel.export.styler.AbstractExcelExportStyler.createStyles(AbstractExcelExportStyler.java:42)
	at org.jeecgframework.poi.excel.export.styler.ExcelExportStylerDefaultImpl.<init>(ExcelExportStylerDefaultImpl.java:31)
	... 93 common frames omitted
2019-08-29 11:55:41.505 ERROR org.jeecgframework.poi.excel.export.ExcelExportServer Line:172 - null
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45009)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45012)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jeecgframework.poi.excel.export.ExcelExportServer.createSheet(ExcelExportServer.java:125)
	at org.jeecgframework.poi.excel.ExcelExportUtil.exportExcel(ExcelExportUtil.java:64)
	at org.jeecgframework.poi.excel.view.JeecgEntityExcelView.renderMergedOutputModel(JeecgEntityExcelView.java:61)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1370)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1116)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by zhangdaiscott** [comment]
你跟这个问题正好相反 https://github.com/zhangdaiscott/jeecg-boot/issues/477

**Comment by brade080710** [comment]
那怎么处理哟

**Comment by zhangdaiscott** [comment]
得告诉我怎么重现

**Comment by brade080710** [comment]
上面代码已贴出来了，随便导出就报上面异常，即使不传任何参数

**Comment by zhangdaiscott** [comment]
你的如果是2.0.2版本，这块功能应该很稳定，不应该有问题

**Comment by kangshifu1** [comment]
导出没这个问题的哇  生成的代码直接就导出了。

**Comment by brade080710** [comment]
找到原因了，poi版本问题
