### ISSUE TITLE
批量更新接口报错异常

### ISSUE THREAD

**Issue by awayzhou** [zhangdaiscott/jeecg-boot#498]
##### 版本号：
2.0.0

##### 问题描述：
mybatis-plus集成y有问题，批量更新接口调用会异常
Parameter 'param1' not found. Available parameters are [et]
我下载了mybatis-plus官网的例子，可以批量更新。
##### 截图&代码：
批量更新失败截图

官网例子更新成功截图

**Comment by zhangdaiscott** [comment]
请补充截图和错误日志

**Comment by awayzhou** [comment]
本项目失败截图
官方例子成功截图



awayzhou@126.com
 
发件人： JEECG开源社区
发送时间： 2019-09-01 18:15
收件人： zhangdaiscott/jeecg-boot
抄送： awayzhou; Author
主题： Re: [zhangdaiscott/jeecg-boot] 批量更新接口报错异常 (#498)
请补充截图和错误日志

**Comment by awayzhou** [comment]
错误日志见附件



awayzhou@126.com
 
发件人： JEECG开源社区
发送时间： 2019-09-01 18:15
收件人： zhangdaiscott/jeecg-boot
抄送： awayzhou; Author
主题： Re: [zhangdaiscott/jeecg-boot] 批量更新接口报错异常 (#498)
请补充截图和错误日志

**Comment by zhangdaiscott** [comment]
还是没图

**Comment by awayzhou** [comment]
请看附件日志


awayzhou@126.com
 
发件人： JEECG开源社区
发送时间： 2019-09-02 15:12
收件人： zhangdaiscott/jeecg-boot
抄送： awayzhou; Author
主题： Re: [zhangdaiscott/jeecg-boot] 批量更新接口报错异常 (#498)
还是没图

**Comment by awayzhou** [comment]
2019-08-31 23:13:33.627 [http-nio-9080-exec-1] DEBUG com.alibaba.druid.pool.PreparedStatementPool:129 - {conn-10004, pstmt-20012} enter cache
2019-08-31 23:13:33.629 [http-nio-9080-exec-1] DEBUG org.mybatis.spring.SqlSessionUtils:186 - Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe99be2]
2019-08-31 23:13:33.630 [http-nio-9080-exec-1] DEBUG org.jeecg.config.mybatis.MybatisInterceptor:39 - ------sqlId------org.jeecg.modules.storage.mapper.StorageProductManageMapper.updateById
2019-08-31 23:13:33.632 [http-nio-9080-exec-1] DEBUG org.jeecg.config.mybatis.MybatisInterceptor:42 - ------sqlCommandType------UPDATE
2019-08-31 23:13:33.636 [http-nio-9080-exec-1] DEBUG o.s.jdbc.datasource.DataSourceTransactionManager:845 - Participating transaction failed - marking existing transaction as rollback-only
2019-08-31 23:13:33.637 [http-nio-9080-exec-1] DEBUG o.s.jdbc.datasource.DataSourceTransactionManager:355 - Setting JDBC transaction [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1ab0d217] rollback-only
2019-08-31 23:13:33.639 [http-nio-9080-exec-1] DEBUG org.mybatis.spring.SqlSessionUtils:310 - Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe99be2]
2019-08-31 23:13:33.640 [http-nio-9080-exec-1] DEBUG org.mybatis.spring.SqlSessionUtils:315 - Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe99be2]
2019-08-31 23:13:33.640 [http-nio-9080-exec-1] DEBUG o.s.jdbc.datasource.DataSourceTransactionManager:836 - Initiating transaction rollback
2019-08-31 23:13:33.641 [http-nio-9080-exec-1] DEBUG o.s.jdbc.datasource.DataSourceTransactionManager:341 - Rolling back JDBC transaction on Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1ab0d217]
2019-08-31 23:13:33.687 [http-nio-9080-exec-1] DEBUG druid.sql.Connection:129 - {conn 10004} rollback
2019-08-31 23:13:33.688 [http-nio-9080-exec-1] DEBUG druid.sql.Connection:129 - {conn-10004} setAutoCommit true
2019-08-31 23:13:33.772 [http-nio-9080-exec-1] DEBUG o.s.jdbc.datasource.DataSourceTransactionManager:384 - Releasing JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@1ab0d217] after transaction
2019-08-31 23:13:33.774 [http-nio-9080-exec-1] DEBUG druid.sql.Connection:129 - {conn-10004} pool-recycle
2019-08-31 23:13:33.779 [http-nio-9080-exec-1] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver:403 - Using @ExceptionHandler public org.jeecg.common.api.vo.Result<?> org.jeecg.common.exception.JeecgBootExceptionHandler.handleException(java.lang.Exception)
2019-08-31 23:13:33.785 [http-nio-9080-exec-1] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:54 - 
### Error updating database.  Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
### Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
### Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.saveOrUpdateBatch(ServiceImpl.java:178)
at com.baomidou.mybatisplus.extension.service.IService.saveOrUpdateBatch(IService.java:76)
at org.jeecg.modules.storage.service.impl.StorageProductManageServiceImpl.saveStorageProductByUpperShelfCode(StorageProductManageServiceImpl.java:74)
at org.jeecg.modules.storage.service.impl.StorageProductManageServiceImpl$$FastClassBySpringCGLIB$$c0cc794b.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.jeecg.modules.storage.service.impl.StorageProductManageServiceImpl$$EnhancerBySpringCGLIB$$124732d3.saveStorageProductByUpperShelfCode(<generated>)
at org.jeecg.modules.storage.service.impl.StorageProductManageServiceImpl$$FastClassBySpringCGLIB$$c0cc794b.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.jeecg.modules.storage.service.impl.StorageProductManageServiceImpl$$EnhancerBySpringCGLIB$$a27b9c03.saveStorageProductByUpperShelfCode(<generated>)
at org.jeecg.modules.storage.controller.StorageProductManageController.saveStorageProductByUpperShelfCode(StorageProductManageController.java:286)
at org.jeecg.modules.storage.controller.StorageProductManageController$$FastClassBySpringCGLIB$$bc2f26c3.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
at org.jeecg.modules.system.aspect.DictAspect.doAround(DictAspect.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
at org.jeecg.modules.system.aspect.AutoLogAspect.around(AutoLogAspect.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.jeecg.modules.storage.controller.StorageProductManageController$$EnhancerBySpringCGLIB$$a6bfe646.saveStorageProductByUpperShelfCode(<generated>)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:77)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:204)
at org.jeecg.config.mybatis.MybatisInterceptor.intercept(MybatisInterceptor.java:109)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy285.update(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
... 140 common frames omitted
2019-08-31 23:13:33.844 [http-nio-9080-exec-1] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor:268 - Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
2019-08-31 23:13:33.846 [http-nio-9080-exec-1] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor:90 - Writing [Result(success=false, message=
### Error updating database.  Cause: org.apache.ibatis.binding.Bindi (truncated)...]
2019-08-31 23:13:33.864 [http-nio-9080-exec-1] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver:143 - Resolved [org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]
### Cause: org.apache.ibatis.binding.BindingException: Parameter 'param1' not found. Available parameters are [et]]
2019-08-31 23:13:33.865 [http-nio-9080-exec-1] DEBUG org.springframework.web.servlet.DispatcherServlet:1130 - Completed 200 OK



awayzhou@126.com
 
发件人： JEECG开源社区
发送时间： 2019-09-02 15:12
收件人： zhangdaiscott/jeecg-boot
抄送： awayzhou; Author
主题： Re: [zhangdaiscott/jeecg-boot] 批量更新接口报错异常 (#498)
还是没图
