### ISSUE TITLE
sqlserver2008启动项目，quartz错误

### ISSUE THREAD

**Issue by ycw01** [zhangdaiscott/jeecg-boot#574]
##### 问题描述：
org.springframework.context.ApplicationContextException: Failed to start bean 'quartzScheduler'; nested exception is org.springframework.scheduling.SchedulingException: Could not start Quartz Scheduler; nested exception is org.quartz.SchedulerConfigException: Failure occured during job recovery. [See nested exception: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: sql injection violation, syntax error: syntax error, not support option : UPDATE, pos 90, line 1, column 84, token UPDATE : SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE [See nested exception: java.sql.SQLException: sql injection violation, syntax error: syntax error, not support option : UPDATE, pos 90, line 1, column 84, token UPDATE : SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME = ? FOR UPDATE]]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.jeecg.JeecgApplication.main(JeecgApplication.java:21)

##### 截图&代码：
JDBC配置
jeecg_database.properties
diver_name=com.microsoft.sqlserver.jdbc.SQLServerDriver
url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=jeecg-boot
username=sa
password=sa
database_name=jeecg-boot

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ycw01** [comment]
补充：以上配置，V2.0.1没有问题

**Comment by zhangdaiscott** [comment]
你用附件的脚步，还原下定时任务相关表，看看

[quartz-2.3.0_sqlServer.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3650921/quartz-2.3.0_sqlServer.zip)

**Comment by ycw01** [comment]
> 你用附件的脚步，还原下定时任务相关表，看看
> 
> [quartz-2.3.0_sqlServer.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3650921/quartz-2.3.0_sqlServer.zip)

还是不行，这是我的数据库备份文件
[jeecg-boot_2019年9月25日145558.zip](https://github.com/zhangdaiscott/jeecg-boot/files/3650951/jeecg-boot_2019.9.25.145558.zip)

**Comment by ycw01** [comment]
我在sqlserver里执行报错的这个语句SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'quartzScheduler' AND LOCK_NAME =‘xx’ FOR UPDATE
报如下错误：
只有 DECLARE CURSOR 才允许使用 FOR UPDATE 子句。

**Comment by zhangdaiscott** [comment]
看看是不是驱动包的问题，
我们现在官方默认针对SqlServer2017进行联调测试

**Comment by ycw01** [comment]
问题原因：
      在Quartz中有一个加锁的SQL语句配置selectWithLockSQL，默认语句为：SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE  
    但是这个语句在低版本的sqlserver中是不支持的
解决方法：
自定义selectWithLockSQL=SELECT* FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?
yml配置如下：
## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore: 
            selectWithLockSQL: SELECT* FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?

万万没想到，我竟然在一个推广网站上找到了答案。。。。
参考地址：http://www.cdxuhang.com/post/68548.html#cmt1

**Comment by zhangdaiscott** [comment]
好的
