### ISSUE TITLE
war包部署时报错，具体报错如下

### ISSUE THREAD

**Issue by wuchao0918** [zhangdaiscott/jeecg-boot#646]
##### 截图&代码：21-Oct-2019 11:39:09.071 严重 [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/jeecg-boot-module-system-2.1.0]]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
at org.apache.catalina.startup.HostConfigDeployWar.run(HostConfig.java:1841)atjava.util.concurrent.ExecutorsDeployWar.run(HostConfig.java:1841)atjava.util.concurrent.ExecutorsRunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)atjava.lang.Thread.run(Thread.java:748)Causedby:org.springframework.beans.factory.BeanCreationException:Errorcreatingbeanwithname′serverEndpointExporter′definedinclasspathresource[org/jeecg/config/WebSocketConfig.class]:Invocationofinitmethodfailed;nestedexceptionisjava.lang.IllegalStateException:javax.websocket.server.ServerContainernotavailableatorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)atorg.springframework.beans.factory.support.AbstractBeanFactory.lambdaWorker.run(ThreadPoolExecutor.java:624)atjava.lang.Thread.run(Thread.java:748)Causedby:org.springframework.beans.factory.BeanCreationException:Errorcreatingbeanwithname′serverEndpointExporter′definedinclasspathresource[org/jeecg/config/WebSocketConfig.class]:Invocationofinitmethodfailed;nestedexceptionisjava.lang.IllegalStateException:javax.websocket.server.ServerContainernotavailableatorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)atorg.springframework.beans.factory.support.AbstractBeanFactory.lambdadoGetBean0(AbstractBeanFactory.java:320)atorg.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)atorg.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)atorg.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)atorg.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)atorg.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)atorg.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)atorg.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)atorg.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)atorg.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)atorg.springframework.boot.SpringApplication.run(SpringApplication.java:316)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)atorg.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)atorg.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)atorg.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)...10moreCausedby:java.lang.IllegalStateException:javax.websocket.server.ServerContainernotavailableatorg.springframework.util.Assert.state(Assert.java:73)atorg.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)...29more21−Oct−201911:39:09.087严重[localhost−startStop−1]org.apache.catalina.startup.HostConfig.deployWARErrordeployingwebapplicationarchive[Z:\apache−tomcat−8.5.43\webapps\jeecg−boot−module−system−2.1.0.war]java.lang.IllegalStateException:ContainerBase.addChild:start:org.apache.catalina.LifecycleException:Failedtostartcomponent[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/jeecg−boot−module−system−2.1.0]]atorg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:747)atorg.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)atorg.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)atorg.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)atorg.apache.catalina.startup.HostConfig0(AbstractBeanFactory.java:320)atorg.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)atorg.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)atorg.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)atorg.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)atorg.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)atorg.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)atorg.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)atorg.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)atorg.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)atorg.springframework.boot.SpringApplication.run(SpringApplication.java:316)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137)atorg.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)atorg.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:171)atorg.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)atorg.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)...10moreCausedby:java.lang.IllegalStateException:javax.websocket.server.ServerContainernotavailableatorg.springframework.util.Assert.state(Assert.java:73)atorg.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)atorg.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)...29more21−Oct−201911:39:09.087严重[localhost−startStop−1]org.apache.catalina.startup.HostConfig.deployWARErrordeployingwebapplicationarchive[Z:\apache−tomcat−8.5.43\webapps\jeecg−boot−module−system−2.1.0.war]java.lang.IllegalStateException:ContainerBase.addChild:start:org.apache.catalina.LifecycleException:Failedtostartcomponent[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/jeecg−boot−module−system−2.1.0]]atorg.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:747)atorg.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)atorg.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)atorg.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)atorg.apache.catalina.startup.HostConfigDeployWar.run(HostConfig.java:1841)
at java.util.concurrent.ExecutorsRunnableAdapter.call(Executors.java:511)atjava.util.concurrent.FutureTask.run(FutureTask.java:266)atjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)atjava.util.concurrent.ThreadPoolExecutorRunnableAdapter.call(Executors.java:511)atjava.util.concurrent.FutureTask.run(FutureTask.java:266)atjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)atjava.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273923
