### ISSUE TITLE
war部署方式错误

### ISSUE THREAD

**Issue by he0128** [zhangdaiscott/jeecg-boot#767]
##### 版本号：
2.1.0

##### 问题描述：
完全按照教程打包部署 报以下错误

##### 截图&代码：
02-Dec-2019 02:20:03.789 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/Users/apple/apache-tomcat-9.0.29/webapps/jeecg-boot.war]
02-Dec-2019 02:20:05.111 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/Users/apple/apache-tomcat-9.0.29/webapps/jeecg-boot.war]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/jeecg-boot]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		... 37 more
	Caused by: java.lang.IllegalArgumentException: Invalid <servlet-name> [] in servlet definition.
		at org.apache.tomcat.util.descriptor.web.ServletDef.setServletName(ServletDef.java:111)
		at org.apache.catalina.startup.ContextConfig.processAnnotationWebServlet(ContextConfig.java:2391)
		at org.apache.catalina.startup.ContextConfig.processClass(ContextConfig.java:2141)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2130)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2022)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2016)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2016)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2016)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2016)
		at org.apache.catalina.startup.ContextConfig.processAnnotationsWebResource(ContextConfig.java:2016)
		at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1233)
		at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1142)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:774)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5051)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 38 more
02-Dec-2019 02:20:05.113 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/Users/apple/apache-tomcat-9.0.29/webapps/jeecg-boot.war] has finished in [1,324] ms
02-Dec-2019 02:20:05.114 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/docs]
02-Dec-2019 02:20:05.229 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/docs] has finished in [115] ms
02-Dec-2019 02:20:05.229 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/manager]
02-Dec-2019 02:20:05.264 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/manager] has finished in [35] ms
02-Dec-2019 02:20:05.264 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/examples]
02-Dec-2019 02:20:05.503 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/examples] has finished in [239] ms
02-Dec-2019 02:20:05.504 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/ROOT]
02-Dec-2019 02:20:05.524 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/ROOT] has finished in [20] ms
02-Dec-2019 02:20:05.525 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/host-manager]
02-Dec-2019 02:20:05.547 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Users/apple/apache-tomcat-9.0.29/webapps/host-manager] has finished in [22] ms
02-Dec-2019 02:20:05.565 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
02-Dec-2019 02:20:05.574 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
02-Dec-2019 02:20:05.576 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,830] milliseconds

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/1273923

**Comment by he0128** [comment]
完全按照你们的教程来的 已部署就报错

**Comment by lsqtzj** [comment]
![image](https://user-images.githubusercontent.com/4635861/95969857-8d214c00-0e0f-11eb-8ca1-7b0595673262.png)
是注释掉这个类吗？完全按照http://doc.jeecg.com/1273923步骤来的，可是还是运行不了。
![image](https://user-images.githubusercontent.com/4635861/95970064-cc4f9d00-0e0f-11eb-9ceb-b2fda93026b1.png)

**Comment by lsqtzj** [comment]
我的找到问题了，原来是平台不支持，瞎折腾。
![image](https://user-images.githubusercontent.com/4635861/95994591-c74f1580-0e30-11eb-9e83-6b17c4e838f1.png)
