### ISSUE TITLE
定时器执行更新操作时报错

### ISSUE THREAD

**Issue by zzs583520** [zhangdaiscott/jeecg-boot#795]
##### 问题描述：在定时任务执行更新操作时报错找不到用户。报错信息如下：
No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
定时任务里面肯定不能获取当前用户

**Comment by zzs583520** [comment]
所以我觉的你们在MybatisInterceptor类里面的“update”有问题的。  定时任务获取不到用户信息怎么添加更新人呢？



zzs583@sina.com
 
发件人： JEECG开源社区
发送时间： 2019-12-10 19:23
收件人： zhangdaiscott/jeecg-boot
抄送： zzs583520; Author
主题： Re: [zhangdaiscott/jeecg-boot] 定时器执行更新操作时报错 (#795)
定时任务里面肯定不能获取当前用户

**Comment by zhangdaiscott** [comment]
详细的报错日志发一下

**Comment by zzs583520** [comment]
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5055ee0f] was not registered for synchronization because synchronization is not active
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the 
org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
at org.apache.shiro.SecurityUtils.getSecurityManager(SecurityUtils.java:123)
at org.apache.shiro.subject.Subject$Builder.<init>(Subject.java:626)
at org.apache.shiro.SecurityUtils.getSubject(SecurityUtils.java:56)
at org.jeecg.config.mybatis.MybatisInterceptor.intercept(MybatisInterceptor.java:146)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy268.update(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
at com.sun.proxy.$Proxy156.update(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:63)
at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
at com.sun.proxy.$Proxy239.updateById(Unknown Source)
at com.baomidou.mybatisplus.extension.service.impl.ServiceImpl.updateById(ServiceImpl.java:207)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl.addYinuoMachineProfit(YinuoMachineProfitServiceImpl.java:150)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl.updateByOrderCode(YinuoMachineProfitServiceImpl.java:98)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl$$FastClassBySpringCGLIB$$7d548b2.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:52)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl$$EnhancerBySpringCGLIB$$bbd6dce8.updateByOrderCode(<generated>)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl$$FastClassBySpringCGLIB$$7d548b2.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:52)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at org.jeecg.modules.finance.service.impl.YinuoMachineProfitServiceImpl$$EnhancerBySpringCGLIB$$75862b92.updateByOrderCode(<generated>)
at org.jeecg.modules.finance.job.MachineProfitJob.addprofit(MachineProfitJob.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@744c16fb] will not be managed by Spring


zzs583@sina.com
 
发件人： zzs583@sina.com
发送时间： 2019-12-11 10:20
收件人： zhangdaiscott/jeecg-boot
主题： Re: Re: [zhangdaiscott/jeecg-boot] 定时器执行更新操作时报错 (#795)
所以我觉的你们在MybatisInterceptor类里面的“update”有问题的。  定时任务获取不到用户信息怎么添加更新人呢？



zzs583@sina.com
 
发件人： JEECG开源社区
发送时间： 2019-12-10 19:23
收件人： zhangdaiscott/jeecg-boot
抄送： zzs583520; Author
主题： Re: [zhangdaiscott/jeecg-boot] 定时器执行更新操作时报错 (#795)
定时任务里面肯定不能获取当前用户

**Comment by zhangdaiscott** [comment]
你是老代码吧

**Comment by zzs583520** [comment]
你确定这是旧代码吗？
附件是我项目的代码。



zzs583@sina.com
 
发件人： JEECG开源社区
发送时间： 2019-12-11 11:07
收件人： zhangdaiscott/jeecg-boot
抄送： zzs583520; Author
主题： Re: [zhangdaiscott/jeecg-boot] 定时器执行更新操作时报错 (#795)
你是老代码吧
―

**Comment by zzs583520** [comment]
我看了你们的新代码，在添加的时候确实考虑了获取不到用户信息的情况，但是在修改的时候没有做相应的处理。
这个是你们最新的代码：



zzs583@sina.com
 
发件人： JEECG开源社区
发送时间： 2019-12-11 11:07
收件人： zhangdaiscott/jeecg-boot
抄送： zzs583520; Author
主题： Re: [zhangdaiscott/jeecg-boot] 定时器执行更新操作时报错 (#795)
你是老代码吧
―

**Comment by rubywu** [comment]
try {
					if ("updateBy".equals(field.getName())) {
						//获取登录用户信息
						LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();
						if (sysUser != null) {
							// 登录账号
							String updateBy = sysUser.getUsername();
							field.setAccessible(true);
							field.set(parameter, updateBy);
							field.setAccessible(false);
						}
					}
					if ("updateTime".equals(field.getName())) {
						field.setAccessible(true);
						field.set(parameter, new Date());
						field.setAccessible(false);
					}
				} catch (Exception e) {
					e.printStackTrace();
				}

修改的代码没更新，在定时器里会报错

**Comment by zhangdaiscott** [comment]
了解，感谢
已改，下个版本发布
