### ISSUE TITLE
代码生成器连接ms sqlserver 2000时，报错

### ISSUE THREAD

**Issue by galaxist** [zhangdaiscott/jeecg-boot#826]
##### 版本号：
2.1.2

##### 问题描述：
报不兼容

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3365218/71303124-4f21ea00-23ef-11ea-9e13-8a0b2a0e2535.png)

****

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by galaxist** [comment]
12:37:25.943 [main] DEBUG com.baomidou.mybatisplus.generator.AutoGenerator - ==========================准备生成文件...==========================
java.sql.SQLException: 对象名 'sys.extended_properties' 无效。

**Comment by galaxist** [comment]
----jeecg--------- Code------------- Generation -----[单表模型]------- 生成中。。。
12:44:10.332 [main] INFO org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne - ----jeecg---Code----Generation----[单表模型:t_item_lb]------- 生成中。。。
java.sql.SQLException: 对象名 'sys.columns' 无效。
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.MSCursorResultSet.processOutput(MSCursorResultSet.java:943)
	at net.sourceforge.jtds.jdbc.MSCursorResultSet.cursorCreate(MSCursorResultSet.java:541)
	at net.sourceforge.jtds.jdbc.MSCursorResultSet.<init>(MSCursorResultSet.java:154)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:452)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeQuery(JtdsStatement.java:1427)
	at org.jeecgframework.codegenerate.database.DbReadTableUtil.a(DbReadTableUtil.java:144)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.a(CodeGenerateOne.java:93)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:126)
	at org.jeecg.modules.storage.erp.bc.pos.generator.BcCodeGenerator.main(BcCodeGenerator.java:30)
----jeecg--------- Code------------- Generation -----[单表模型]------- 生成完成。。。
Disconnected from the target VM, address: '127.0.0.1:59371', transport: 'socket'

Process finished with exit code 0

**Comment by galaxist** [comment]
----jeecg--------- Code------------- Generation -----[单表模型]------- 生成中。。。
12:45:32.105 [main] INFO org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne - ----jeecg---Code----Generation----[单表模型:t_item_lb]------- 生成中。。。
十二月 21, 2019 12:45:33 下午 com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
警告: ConnectionID:1 ClientConnectionId: d8244f00-dcfc-4df6-b1c4-a1ba03584c9b Server major version:8 is not supported by this driver.
com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server version 8 is not supported by this driver. ClientConnectionId:d8244f00-dcfc-4df6-b1c4-a1ba03584c9b
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2392)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2376)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.Prelogin(SQLServerConnection.java:2261)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1965)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1616)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1447)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:788)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1187)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jeecgframework.codegenerate.database.DbReadTableUtil.a(DbReadTableUtil.java:121)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.a(CodeGenerateOne.java:93)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:126)
	at org.jeecg.modules.storage.erp.bc.pos.generator.BcCodeGenerator.main(BcCodeGenerator.java:30)
----jeecg--------- Code------------- Generation -----[单表模型]------- 生成完成。。。
Disconnected from the target VM, address: '127.0.0.1:59603', transport: 'socket'

Process finished with exit code 0

**Comment by galaxist** [comment]
![image](https://user-images.githubusercontent.com/3365218/71303197-36fe9a80-23f0-11ea-868a-e47a8008a117.png)
![image](https://user-images.githubusercontent.com/3365218/71303200-4aaa0100-23f0-11ea-8e27-82a01cd3bc16.png)

**Comment by galaxist** [comment]
<dependency>
      <groupId>net.sourceforge.jtds</groupId>
      <artifactId>jtds</artifactId>
      <version>1.3.1</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>6.1.0.jre8</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>7.4.1.jre8</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>sqljdbc4</artifactId>
      <version>4.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft</groupId>
      <artifactId>sqljdbc4</artifactId>
      <version>3.0</version>
    </dependency>

这些都试验过，统统报错。

**Comment by galaxist** [comment]
检查发现是代码生成器使用查询表字段语句仅在sqlserver2005以上使用。
```
SELECT DISTINCT CAST
	( a.name AS VARCHAR ( 50 ) ) column_name,
	CAST ( b.name AS VARCHAR ( 50 ) ) data_type,
	CAST ( e.value AS VARCHAR ( 200 ) ) comment,
	CAST ( ColumnProperty( a.object_id, a.Name, '''Precision''' ) AS INT ) num_precision,
	CAST ( ColumnProperty( a.object_id, a.Name, '''Scale''' ) AS INT ) num_scale,
	a.max_length,
	( CASE WHEN a.is_nullable= 1 THEN '''y''' ELSE '''n''' END ) nullable,
	column_id 
FROM
	sys.columns a
	LEFT JOIN sys.types b ON a.user_type_id= b.user_type_id
	LEFT JOIN ( SELECT TOP 1 * FROM sys.objects WHERE type = '''U'''  ORDER BY name ) c ON a.object_id = c.object_id
	LEFT JOIN sys.extended_properties e ON e.major_id= c.object_id 
	AND e.minor_id= a.column_id 
	AND e.class= 1 

ORDER BY
	a.column_id
```

在sqlserver2000中仅有syscolumns,systypes，sysobjects

**Comment by ggunmo** [comment]
项目介绍那有写数据库要求
数据库：MySQL5.7+ & Oracle 11g & Sqlserver2017

**Comment by zhangdaiscott** [comment]
的确没办法做到兼容全部版本, Sqlserver老版本和新版语法有区别，我们暂时只支持 Sqlserver2017+
