### ISSUE TITLE
部门管理中以管理员用户登录添加子部门或者添加一级部门操作失败

### ISSUE THREAD

**Issue by liushaowenliushaowen** [zhangdaiscott/jeecg-boot#841]
##### 截图&代码：
java.lang.NullPointerException: null
	at org.jeecg.modules.system.service.impl.SysDepartServiceImpl.saveDepartData(SysDepartServiceImpl.java:86)
	at org.jeecg.modules.system.service.impl.SysDepartServiceImpl$$FastClassBySpringCGLIB$$6f2aae1b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
测试没有问题，你怎么操作的

**Comment by liushaowenliushaowen** [comment]
选择卓尔互动公司下的研发部，添加子部门，填取名称后点击保存

**Comment by zhangdaiscott** [comment]
你应该是没升级数据库
