### ISSUE TITLE
online表单开发，打包后模板找不到

### ISSUE THREAD

**Issue by mamacmm** [zhangdaiscott/jeecg-boot#865]
##### 版本号：
2.1.3

##### 问题描述：
项目打包后，使用jar包方式运行项目，提示找不到，在打的jar包里面是有模板的，但是会报错，是不是FreeMarker模板加载的问题？

##### 截图&代码：
```
java.io.FileNotFoundException: file:/root/workspace/jeecg-boot-module-system.jar!/BOOT-INF/classes!/jeecg/code-template-online/one does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:122)
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:119)
	at java.security.AccessController.doPrivileged(Native Method)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:119)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:98)
	at org.jeecgframework.codegenerate.generate.util.b.a(FreemarkerHelper.java:29)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:208)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:66)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:55)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:39)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:135)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:149)
	at org.jeecg.modules.online.cgform.service.impl.d.generateCode(OnlCgformHeadServiceImpl.java:1150)
	at org.jeecg.modules.online.cgform.service.impl.d$$FastClassBySpringCGLIB$$a1d6ff6b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$8d587b99.generateCode(<generated>)
	at org.jeecg.modules.online.cgform.service.impl.d$$FastClassBySpringCGLIB$$a1d6ff6b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$8c393789.generateCode(<generated>)
	at org.jeecg.modules.online.cgform.a.a.b(OnlCgformApiController.java:1069)
	at org.jeecg.modules.online.cgform.a.a$$FastClassBySpringCGLIB$$b709198.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by zhangdaiscott** [comment]
为什么要在发布环境执行代码生成器？ 不都是开发环境才生成代码吗

**Comment by mamacmm** [comment]
如果能调用打包的模板，可以放到一个测试服务器上，供开发人员生成代码，本地项目可以不用放模板了。
如果生成的代码能有个按钮下载就更好了

**Comment by wdyoschina** [comment]
@zhangdaiscott  我也遇到相同问题，请问题这种问题该怎么解决？

**Comment by zhangdaiscott** [comment]
目前没实现这个功能，我们考虑下

**Comment by wdyoschina** [comment]
@zhangdaiscott 谢谢！
也就是说“在线代码生成”功能只能在开发环境，或者说是在所有配置都是localhost的情况下才能使用吗？

**Comment by mamacmm** [comment]
@zhangdaiscott 谢谢！

**Comment by wdyoschina** [comment]
本地运行，还是会报同样的错误！代码自动生成不能使用呢！
codegenerate-1.0.8.jar!\jeecg\code-template\one does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:122)
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:119)
	at java.security.AccessController.doPrivileged(Native Method)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:119)
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:98)
	at org.jeecgframework.codegenerate.generate.util.b.a(FreemarkerHelper.java:29)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:208)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:66)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:55)
	at org.jeecgframework.codegenerate.generate.impl.a.a.a(BaseCodeGenerate.java:39)
	at org.jeecgframework.codegenerate.generate.impl.CodeGenerateOne.generateCodeFile(CodeGenerateOne.java:135)
	at org.jeecgframework.codegenerate.window.CodeWindow$1.actionPerformed(CodeWindow.java:189)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by zhangdaiscott** [comment]
下个版本出解决方案

**Comment by BeginnerA** [comment]
你好博主我开发环境下也找不到模板是什么原因（code-template-online does not exist）
