### ISSUE TITLE
CAS单点登录对接之后后端启动报错

### ISSUE THREAD

**Issue by lifuchao** [zhangdaiscott/jeecg-boot#904]
##### 版本号：
2.1.3

##### 问题描述：
如题，参考文档来做的http://doc.jeecg.com/1273851，前后端的代码该改的都改了。
其中CAS的搭建我是参考https://blog.csdn.net/zzy730913/article/details/80796716 来做的，能正常登录进去了，确认CAS部署正常；

##### 截图&代码：
（1）文档中说支持CAS5.2X和5.3X,我一开始服务端用的5.3.14，pom里的依赖试过5.3.15和5.3.0，启动报错如下
![image](https://user-images.githubusercontent.com/15504114/72702141-9d600f80-3b8c-11ea-8fc5-89abb6042352.png)

（2）然后尝试用CAS用5.2.6，pom依赖用5.2.6和5.2.9都试过。
启动过程中间报错如下
![image](https://user-images.githubusercontent.com/15504114/72702205-cc768100-3b8c-11ea-89e2-c20b8276ef5d.png)

并没有mongo啊，为什么回去尝试连接mongo？
然后后面又有报错
![image](https://user-images.githubusercontent.com/15504114/72702331-4444ab80-3b8d-11ea-8924-fc65fb2cf476.png)

截图可能看不全，报错信息：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-20 14:11:16.813 [restartedMain] ERROR org.springframework.boot.SpringApplication:821 - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'onlCgformApiController': Unsatisfied dependency expressed through field 'onlCgformHeadService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/lkk/.m2/repository/org/hibernate/hibernate-re/5.2.13/hibernate-re-5.2.13.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at org.jeecg.JeecgApplication.main(JeecgApplication.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/lkkk/.m2/repository/org/hibernate/hibernate-re/5.2.13/hibernate-re-5.2.13.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 24 common frames omitted
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:214)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:471)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:350)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:57)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205)
	... 40 common frames omitted
Caused by: java.lang.LinkageError: loader constraint violation: when resolving overridden method "org.jeecg.modules.online.cgform.service.impl.d$$EnhancerBySpringCGLIB$$6a1723dc.addAll(Lorg/jeecg/modules/online/cgform/model/a;)Lorg/jeecg/common/api/vo/Result;" the class loader (instance of org/springframework/boot/devtools/restart/classloader/RestartClassLoader) of the current class, org/jeecg/modules/online/cgform/service/impl/d$$EnhancerBySpringCGLIB$$6a1723dc, and its superclass loader (instance of sun/misc/Launcher$AppClassLoader), have different Class objects for the type org/jeecg/common/api/vo/Result used in the signature
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:563)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:582)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	... 47 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:65367', transport: 'socket'

想问下你们实际对接的具体是什么版本？我的问题可能出在什么地方？麻烦指点下啊，谢谢了先

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你是服务端的程序有问题？数据库链接失败

**Comment by lifuchao** [comment]
> 你是服务端的程序有问题？数据库链接失败
后端启动报错啊，我的多数据源数据库连接都没有问题，只要把cam的相关依赖去掉，我整个项目都没问题的，所以并非数据库连接失败啊。你的意思难道是CAS依赖mongo吗，要装个mongo?
问题怎么就关闭了啊？
重点在这一句吧，但没找到问题所在：
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'onlCgformHeadServiceImpl' defined in URL [jar:file:/C:/Users/lkkk/.m2/repository/org/hibernate/hibernate-re/5.2.13/hibernate-re-5.2.13.jar!/org/jeecg/modules/online/cgform/service/impl/d.class]: I

**Comment by zhangdaiscott** [comment]
服务端我们不提供支持，你是自己的代码，自己研究吧

**Comment by lifuchao** [comment]
> 后端是你自己的代码，我们没办法判断，所以不提供支持，自己研究吧

-------------------------------------------------------------------------
我环境是Jeecg2.1.3，CAS是5.2.6，我现在配好了CAS用域名访问，也启用了restful配置，用postman生成了ST，然后在你们已有的CASServiceUtil测了是正常的。
![image](https://user-images.githubusercontent.com/15504114/74706526-216fea80-5252-11ea-8408-8500a6ad4e35.png)

但是整个后端项目还是一启动就报错，报错信息还是就跟之前发的一样。我想问问这是什么问题了，是jeecg版本的问题吗？我就是按你们官网的“CAS单点登录对接”来弄的，也没改什么啊。麻烦指点下，给个研究思路啊，多谢了先

**Comment by zhang-jc** [comment]
@lifuchao 
![Uploading 2022-09-04_02-11.png…]()

**Comment by UsernameUntaken** [comment]
请问下，后来打开那个，正常解决了吗，我也想参考你的那个来弄来着


另外 http://doc.jeecg.com/1273851 现在访问不了了 404
